import { describe, expect, it } from "vitest";
import { executeMonitoringEvent, MonitoringEvent, MonitoringStore } from "../lib/monitoring-execution";

const event = (overrides: Partial<MonitoringEvent> = {}): MonitoringEvent => ({ eventId: "evt-1", tenantId: "tenant-a", employeeId: "support_agent", connectionId: "conn-a", providerId: "zendesk", objectType: "ticket", eventType: "created", occurredAt: "2026-08-02T00:00:00Z", receivedAt: "2026-08-02T00:00:01Z", payloadHash: "hash", provenance: "provider_webhook", authenticated: true, payload: { ticketId: "t-1" }, ...overrides });
function store(): MonitoringStore & { records: string[]; audits: string[] } { const records: string[] = []; const audits: string[] = []; return { records, audits, async hasProcessed(key) { return records.includes(key); }, async record(_e, key, outcome) { records.push(key); records.push(outcome); }, async audit(_e, outcome) { audits.push(outcome); } }; }
const adapters = [{ providerId: "zendesk", objectTypes: ["ticket"], eventTypes: ["created"] }] as const;
const gate = { purchased: true, employeeStatus: "Active" as const, connectionTenantId: "tenant-a", connectionActive: true };

describe("tenant-scoped monitoring execution", () => {
  it("queues an authenticated purchased active event and redacts audit", async () => { const s = store(); const result = await executeMonitoringEvent(event(), gate, adapters, s, async () => {}); expect(result.outcome).toBe("queued"); expect(result.attempts).toBe(1); expect(s.audits).toEqual(["queued"]); });
  it("fails closed for paused, unentitled, cross-tenant and unsupported events", async () => { for (const [e, g, expected] of [[event(), { ...gate, employeeStatus: "Paused" as const }, "skipped_paused"], [event(), { ...gate, purchased: false }, "skipped_unentitled"], [event(), { ...gate, connectionTenantId: "tenant-b" }, "skipped_unentitled"], [event({ eventType: "deleted" }), gate, "skipped_unsupported"]] as const) { const s = store(); expect((await executeMonitoringEvent(e, g, adapters, s, async () => { throw new Error("must not dispatch"); })).outcome).toBe(expected); } });
  it("deduplicates and retries only transient failures", async () => { const s = store(); let attempts = 0; const first = await executeMonitoringEvent(event(), gate, adapters, s, async () => { attempts++; const error = new Error("temporary"); error.name = "TransientMonitoringError"; throw error; }); expect(first.outcome).toBe("failed"); expect(first.attempts).toBe(3); const duplicate = await executeMonitoringEvent(event(), gate, adapters, s, async () => { throw new Error("must not dispatch"); }); expect(duplicate.outcome).toBe("deduped"); expect(attempts).toBe(3); });
  it("rejects unauthenticated events without dispatch", async () => { const s = store(); const result = await executeMonitoringEvent(event({ authenticated: false }), gate, adapters, s, async () => { throw new Error("must not dispatch"); }); expect(result.outcome).toBe("skipped_unsupported"); });
});
