import { describe, expect, it } from "vitest";
import { procurementCapabilities, readPurchaseOrders, createPurchaseOrder, monitorPurchaseOrders } from "../agents/capabilities/procurement";
describe("Procurement / Coupa capability slice", () => {
 it("keeps contracts unverified", () => expect(procurementCapabilities.map(c=>c.status)).toEqual(["unverified","unverified","unverified"]));
 it("has monitor contract with correct capabilityId", () => { const m=procurementCapabilities.find(c=>c.capabilityId==="coupa-monitor-purchase-orders"); expect(m).toBeDefined(); expect(m!.kind).toBe("monitor"); });
 it("fails closed without tenant or auth", async()=>{ const a={listPurchaseOrders:async()=>[]} as any; await expect(readPurchaseOrders(a,{tenantId:"",authToken:"x",audit:()=>{}})).rejects.toThrow("Tenant scope"); await expect(readPurchaseOrders(a,{tenantId:"t",audit:()=>{}})).rejects.toThrow("authentication"); });
 it("retries bounded reads and audits", async()=>{let calls=0;const out:string[]=[];const r=await readPurchaseOrders({listPurchaseOrders:async t=>{calls++;expect(t).toBe("t");if(calls<2)throw Error("temporary");return ["po"];}},{tenantId:"t",authToken:"token",maxAttempts:2,audit:e=>out.push(e.outcome)});expect(r).toEqual(["po"]);expect(calls).toBe(2);expect(out).toEqual(["succeeded"]);});
 it("requires idempotency and audits failed writes", async()=>{const out:string[]=[];const a={createPurchaseOrder:async()=>{throw Error("unavailable")}};await expect(createPurchaseOrder(a,{}, {tenantId:"t",authToken:"token",audit:e=>out.push(e.outcome)},"")).rejects.toThrow("Idempotency");await expect(createPurchaseOrder(a,{}, {tenantId:"t",authToken:"token",maxAttempts:2,audit:e=>out.push(e.outcome)},"k")).rejects.toThrow("unavailable");expect(out).toEqual(["failed"]);});
 it("monitor fails closed without tenant or auth", async()=>{ const a={monitorPurchaseOrders:async()=>[]} as any; await expect(monitorPurchaseOrders(a,{tenantId:"",authToken:"x",audit:()=>{}})).rejects.toThrow("Tenant scope"); await expect(monitorPurchaseOrders(a,{tenantId:"t",audit:()=>{}})).rejects.toThrow("authentication"); });
 it("monitor retries and audits on success", async()=>{let calls=0;const out:string[]=[];const r=await monitorPurchaseOrders({monitorPurchaseOrders:async t=>{calls++;expect(t).toBe("t");if(calls<2)throw Error("temporary");return [{id:"po1"},{id:"po2"}];}},{tenantId:"t",authToken:"token",maxAttempts:2,audit:e=>out.push(e.outcome)});expect(r).toEqual([{id:"po1"},{id:"po2"}]);expect(calls).toBe(2);expect(out).toEqual(["succeeded"]);});
 it("monitor audits failure after all retries", async()=>{const out:string[]=[];const a={monitorPurchaseOrders:async()=>{throw Error("unavailable")}};await expect(monitorPurchaseOrders(a,{tenantId:"t",authToken:"token",maxAttempts:2,audit:e=>out.push(e.outcome)})).rejects.toThrow("unavailable");expect(out).toEqual(["failed"]);});
});
