import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";
export const COMMUNICATIONS_EMPLOYEE_ID = "communications";
export const SLACK_PROVIDER_ID = "slack";
export const communicationsCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: COMMUNICATIONS_EMPLOYEE_ID, capabilityId: "slack-read-messages", kind: "understand", status: "unverified", providerId: SLACK_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "Slack provider module exposes channel message read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: COMMUNICATIONS_EMPLOYEE_ID, capabilityId: "slack-send-message", kind: "automate", status: "unverified", providerId: SLACK_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "Slack provider module exposes message send capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface CommunicationsAdapter { listMessages(tenantId: string): Promise<unknown>; sendMessage(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface CommunicationsExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: CommunicationsExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readMessages(adapter: CommunicationsAdapter, options: CommunicationsExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt=0; attempt<boundedAttempts(options.maxAttempts); attempt++) { try { const result=await adapter.listMessages(options.tenantId); await options.audit({capabilityId:"slack-read-messages",tenantId:options.tenantId,outcome:"succeeded"}); return result; } catch(error) { lastError=error; } } await options.audit({capabilityId:"slack-read-messages",tenantId:options.tenantId,outcome:"failed"}); throw lastError; }
export async function sendMessage(adapter: CommunicationsAdapter, input: Record<string, unknown>, options: CommunicationsExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt=0; attempt<boundedAttempts(options.maxAttempts); attempt++) { try { const result=await adapter.sendMessage(options.tenantId,input,idempotencyKey); await options.audit({capabilityId:"slack-send-message",tenantId:options.tenantId,outcome:"succeeded",idempotencyKey}); return result; } catch(error) { lastError=error; } } await options.audit({capabilityId:"slack-send-message",tenantId:options.tenantId,outcome:"failed",idempotencyKey}); throw lastError; }
