import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";
export const COMPLIANCE_EMPLOYEE_ID = "compliance";
export const JIRA_PROVIDER_ID = "jira";
export const complianceCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: COMPLIANCE_EMPLOYEE_ID, capabilityId: "jira-read-audit-items", kind: "understand", status: "unverified", providerId: JIRA_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "Jira provider module exposes audit-item read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: COMPLIANCE_EMPLOYEE_ID, capabilityId: "jira-create-audit-finding", kind: "automate", status: "unverified", providerId: JIRA_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "Jira provider module exposes audit-finding creation capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface ComplianceAdapter { listAuditItems(tenantId: string): Promise<unknown>; createAuditFinding(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface ComplianceExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: ComplianceExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readAuditItems(adapter: ComplianceAdapter, options: ComplianceExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.listAuditItems(options.tenantId); await options.audit({ capabilityId: "jira-read-audit-items", tenantId: options.tenantId, outcome: "succeeded" }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "jira-read-audit-items", tenantId: options.tenantId, outcome: "failed" }); throw lastError; }
export async function createAuditFinding(adapter: ComplianceAdapter, input: Record<string, unknown>, options: ComplianceExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.createAuditFinding(options.tenantId, input, idempotencyKey); await options.audit({ capabilityId: "jira-create-audit-finding", tenantId: options.tenantId, outcome: "succeeded", idempotencyKey }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "jira-create-audit-finding", tenantId: options.tenantId, outcome: "failed", idempotencyKey }); throw lastError; }
