import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";

export const DOCUMENT_PROCESSING_EMPLOYEE_ID = "document_processing";
export const DOCUSIGN_PROVIDER_ID = "docusign";
export const documentProcessingCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: DOCUMENT_PROCESSING_EMPLOYEE_ID, capabilityId: "docusign-read-envelopes", kind: "understand", status: "unverified", providerId: DOCUSIGN_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "DocuSign provider module exposes envelope read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: DOCUMENT_PROCESSING_EMPLOYEE_ID, capabilityId: "docusign-send-document", kind: "automate", status: "unverified", providerId: DOCUSIGN_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "DocuSign provider module exposes envelope sending capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface DocumentProcessingAdapter { listEnvelopes(tenantId: string): Promise<unknown>; sendDocument(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface DocumentProcessingExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: DocumentProcessingExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readEnvelopes(adapter: DocumentProcessingAdapter, options: DocumentProcessingExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.listEnvelopes(options.tenantId); await options.audit({ capabilityId: "docusign-read-envelopes", tenantId: options.tenantId, outcome: "succeeded" }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "docusign-read-envelopes", tenantId: options.tenantId, outcome: "failed" }); throw lastError; }
export async function sendDocument(adapter: DocumentProcessingAdapter, input: Record<string, unknown>, options: DocumentProcessingExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.sendDocument(options.tenantId, input, idempotencyKey); await options.audit({ capabilityId: "docusign-send-document", tenantId: options.tenantId, outcome: "succeeded", idempotencyKey }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "docusign-send-document", tenantId: options.tenantId, outcome: "failed", idempotencyKey }); throw lastError; }
