import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";
export const HR_COORDINATOR_EMPLOYEE_ID = "hr_coordinator";
export const WORKDAY_PROVIDER_ID = "workday";
export const hrCoordinatorCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: HR_COORDINATOR_EMPLOYEE_ID, capabilityId: "workday-read-employees", kind: "understand", status: "unverified", providerId: WORKDAY_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "Workday provider module exposes employee read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: HR_COORDINATOR_EMPLOYEE_ID, capabilityId: "workday-update-employee", kind: "automate", status: "unverified", providerId: WORKDAY_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "Workday provider module exposes employee update capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface HrCoordinatorAdapter { listEmployees(tenantId: string): Promise<unknown>; updateEmployee(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface HrCoordinatorExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: HrCoordinatorExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readEmployees(adapter: HrCoordinatorAdapter, options: HrCoordinatorExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.listEmployees(options.tenantId); await options.audit({ capabilityId: "workday-read-employees", tenantId: options.tenantId, outcome: "succeeded" }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "workday-read-employees", tenantId: options.tenantId, outcome: "failed" }); throw lastError; }
export async function updateEmployee(adapter: HrCoordinatorAdapter, input: Record<string, unknown>, options: HrCoordinatorExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.updateEmployee(options.tenantId, input, idempotencyKey); await options.audit({ capabilityId: "workday-update-employee", tenantId: options.tenantId, outcome: "succeeded", idempotencyKey }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "workday-update-employee", tenantId: options.tenantId, outcome: "failed", idempotencyKey }); throw lastError; }
