import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";
export const MARKETING_EMPLOYEE_ID = "marketing";
export const MARKETO_PROVIDER_ID = "marketo";
export const marketingCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: MARKETING_EMPLOYEE_ID, capabilityId: "marketo-read-campaigns", kind: "understand", status: "unverified", providerId: MARKETO_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "Marketo provider module exposes campaign read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: MARKETING_EMPLOYEE_ID, capabilityId: "marketo-send-email", kind: "automate", status: "unverified", providerId: MARKETO_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "Marketo provider module exposes campaign email sending capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface MarketingAdapter { listCampaigns(tenantId: string): Promise<unknown>; sendEmail(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface MarketingExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: MarketingExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readCampaigns(adapter: MarketingAdapter, options: MarketingExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt=0; attempt<boundedAttempts(options.maxAttempts); attempt++) { try { const result=await adapter.listCampaigns(options.tenantId); await options.audit({capabilityId:"marketo-read-campaigns",tenantId:options.tenantId,outcome:"succeeded"}); return result; } catch(error) { lastError=error; } } await options.audit({capabilityId:"marketo-read-campaigns",tenantId:options.tenantId,outcome:"failed"}); throw lastError; }
export async function sendEmail(adapter: MarketingAdapter, input: Record<string, unknown>, options: MarketingExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt=0; attempt<boundedAttempts(options.maxAttempts); attempt++) { try { const result=await adapter.sendEmail(options.tenantId,input,idempotencyKey); await options.audit({capabilityId:"marketo-send-email",tenantId:options.tenantId,outcome:"succeeded",idempotencyKey}); return result; } catch(error) { lastError=error; } } await options.audit({capabilityId:"marketo-send-email",tenantId:options.tenantId,outcome:"failed",idempotencyKey}); throw lastError; }
