import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";
export interface ExpansionOptions { tenantId: string; authToken?: string; audit: (event:{capabilityId:string;tenantId:string;outcome:string;idempotencyKey?:string})=>Promise<void>|void; maxAttempts?: number; }
export type ExpansionAdapter = (method:string, tenantId:string, input?:Record<string,unknown>, key?:string)=>Promise<unknown>;
const contract=(employeeId:string,providerId:string,capabilityId:string,kind:"understand"|"automate"):CapabilityContract=>defineCapabilityContract({employeeId,providerId,capabilityId,kind,status:"unverified",tenantScoped:true,authRequired:true,auditRequired:true,idempotencyRequired:kind==="automate",retryPolicy:"bounded",rollback:kind==="automate"?"available":"not_applicable",evidence:`${providerId} provider capability ${capabilityId} evidence is pending.`});
const ids={logistics:["onfleet","read-workers","read-teams","update-task-status","read-routes"],manufacturing:["shopify","read-inventory","read-fulfillments","update-fulfillment","read-product-variants"],procurement:["coupa","read-suppliers","read-receipts","read-invoices-against-po","read-approval-chains"],customer_success:["intercom","read-contacts","read-companies","assign-conversation","tag-user"],operations:["monday","read-column-values","update-column-values","move-item","read-subitems","read-workspaces"],finance:["quickbooks","read-chart-of-accounts","read-profit-loss","read-balance-sheet","read-bills","reconcile-bank-feed"]} as const;
function contracts(employeeId:string,providerId:string,names:readonly string[]):ReadonlyArray<CapabilityContract>{return names.map((name,i)=>contract(employeeId,providerId,`${providerId}-${name}`,i>=2&&["update-task-status","update-fulfillment","assign-conversation","tag-user","update-column-values","move-item","reconcile-bank-feed"].includes(name)?"automate":"understand"));}
export const phase1bCapabilities={logistics:contracts("logistics",ids.logistics[0],ids.logistics.slice(1)),manufacturing:contracts("manufacturing",ids.manufacturing[0],ids.manufacturing.slice(1)),procurement:contracts("procurement",ids.procurement[0],ids.procurement.slice(1)),customer_success:contracts("customer_success",ids.customer_success[0],ids.customer_success.slice(1)),operations:contracts("operations",ids.operations[0],ids.operations.slice(1)),finance:contracts("finance",ids.finance[0],ids.finance.slice(1))} as const;
const WRITE_METHODS=new Set(["update-task-status","update-fulfillment","assign-conversation","tag-user","update-column-values","move-item","reconcile-bank-feed"]);
function requireAuth(o:ExpansionOptions){if(!o.tenantId.trim())throw Error("Tenant scope is required");if(!o.authToken?.trim())throw Error("Provider authentication is required");}
export async function executeExpansion(adapter:ExpansionAdapter,method:string,options:ExpansionOptions,input:Record<string,unknown>={},key?:string):Promise<unknown>{requireAuth(options);if(WRITE_METHODS.has(method)&&!key?.trim())throw Error("Idempotency key is required");let last:unknown;for(let i=0;i<Math.max(1,Math.min(options.maxAttempts??2,3));i++){try{const r=await adapter(method,options.tenantId,input,key);await options.audit({capabilityId:method,tenantId:options.tenantId,outcome:"succeeded",...(key?{idempotencyKey:key}:{})});return r;}catch(e){last=e;}}await options.audit({capabilityId:method,tenantId:options.tenantId,outcome:"failed",...(key?{idempotencyKey:key}:{})});throw last;}
