import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";
export const PROCUREMENT_EMPLOYEE_ID = "procurement";
export const COUPA_PROVIDER_ID = "coupa";
export const procurementCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: PROCUREMENT_EMPLOYEE_ID, capabilityId: "coupa-read-purchase-orders", kind: "understand", status: "unverified", providerId: COUPA_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "Coupa provider module exposes purchase-order read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: PROCUREMENT_EMPLOYEE_ID, capabilityId: "coupa-create-purchase-order", kind: "automate", status: "unverified", providerId: COUPA_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "Coupa provider module exposes purchase-order creation capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface ProcurementAdapter { listPurchaseOrders(tenantId: string): Promise<unknown>; createPurchaseOrder(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface ProcurementExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: ProcurementExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readPurchaseOrders(adapter: ProcurementAdapter, options: ProcurementExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt=0; attempt<boundedAttempts(options.maxAttempts); attempt++) { try { const result=await adapter.listPurchaseOrders(options.tenantId); await options.audit({capabilityId:"coupa-read-purchase-orders",tenantId:options.tenantId,outcome:"succeeded"}); return result; } catch(error) { lastError=error; } } await options.audit({capabilityId:"coupa-read-purchase-orders",tenantId:options.tenantId,outcome:"failed"}); throw lastError; }
export async function createPurchaseOrder(adapter: ProcurementAdapter, input: Record<string, unknown>, options: ProcurementExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt=0; attempt<boundedAttempts(options.maxAttempts); attempt++) { try { const result=await adapter.createPurchaseOrder(options.tenantId,input,idempotencyKey); await options.audit({capabilityId:"coupa-create-purchase-order",tenantId:options.tenantId,outcome:"succeeded",idempotencyKey}); return result; } catch(error) { lastError=error; } } await options.audit({capabilityId:"coupa-create-purchase-order",tenantId:options.tenantId,outcome:"failed",idempotencyKey}); throw lastError; }
