import { defineCapabilityContract, type CapabilityContract } from "../../lib/capability-contract";

export const SALES_EMPLOYEE_ID = "sales";
export const SALESFORCE_PROVIDER_ID = "salesforce";
export const salesCapabilities: ReadonlyArray<CapabilityContract> = [
  defineCapabilityContract({ employeeId: SALES_EMPLOYEE_ID, capabilityId: "salesforce-read-opportunities", kind: "understand", status: "unverified", providerId: SALESFORCE_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: false, retryPolicy: "bounded", rollback: "not_applicable", evidence: "Salesforce provider module exposes opportunity read capability; authorized tenant read evidence is pending." }),
  defineCapabilityContract({ employeeId: SALES_EMPLOYEE_ID, capabilityId: "salesforce-update-opportunity", kind: "automate", status: "unverified", providerId: SALESFORCE_PROVIDER_ID, tenantScoped: true, authRequired: true, auditRequired: true, idempotencyRequired: true, retryPolicy: "bounded", rollback: "available", evidence: "Salesforce provider module exposes opportunity update capability; authorized write, idempotency, and rollback evidence is pending." }),
];
export interface SalesAdapter { listOpportunities(tenantId: string): Promise<unknown>; updateOpportunity(tenantId: string, input: Record<string, unknown>, idempotencyKey: string): Promise<unknown>; }
export interface SalesExecutionOptions { tenantId: string; authToken?: string; audit: (event: { capabilityId: string; tenantId: string; outcome: string; idempotencyKey?: string }) => Promise<void> | void; maxAttempts?: number; }
function requireTenant(options: SalesExecutionOptions): void { if (!options.tenantId.trim()) throw new Error("Tenant scope is required"); if (!options.authToken?.trim()) throw new Error("Provider authentication is required"); }
function boundedAttempts(value?: number): number { return Math.max(1, Math.min(value ?? 2, 3)); }
export async function readOpportunities(adapter: SalesAdapter, options: SalesExecutionOptions): Promise<unknown> { requireTenant(options); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.listOpportunities(options.tenantId); await options.audit({ capabilityId: "salesforce-read-opportunities", tenantId: options.tenantId, outcome: "succeeded" }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "salesforce-read-opportunities", tenantId: options.tenantId, outcome: "failed" }); throw lastError; }
export async function updateOpportunity(adapter: SalesAdapter, input: Record<string, unknown>, options: SalesExecutionOptions, idempotencyKey: string): Promise<unknown> { requireTenant(options); if (!idempotencyKey.trim()) throw new Error("Idempotency key is required"); let lastError: unknown; for (let attempt = 0; attempt < boundedAttempts(options.maxAttempts); attempt++) { try { const result = await adapter.updateOpportunity(options.tenantId, input, idempotencyKey); await options.audit({ capabilityId: "salesforce-update-opportunity", tenantId: options.tenantId, outcome: "succeeded", idempotencyKey }); return result; } catch (error) { lastError = error; } } await options.audit({ capabilityId: "salesforce-update-opportunity", tenantId: options.tenantId, outcome: "failed", idempotencyKey }); throw lastError; }
