export interface IndustryResource {
  id: string;
  industry: string[];
  topAutomations: { name: string; timeSaved: string; difficulty: "easy" | "medium" | "hard" }[];
  roiCalculatorConfig: {
    avgHourlyRate: number;
    typicalHoursPerWeek: number;
    implementationWeeks: number;
    savingsMultiplier: number;
    breakEvenMonths: number;
  };
  checklistTopics: string[];
  caseStudySnippets: string[];
  commonIntegrations: string[];
  faqs: { question: string; answer: string }[];
}

export const industryResources: IndustryResource[] = [
  {
    id: "manufacturing",
    industry: ["manufacturing"],
    topAutomations: [
      { name: "Invoice Processing Automation", timeSaved: "18 hrs/week", difficulty: "medium" },
      { name: "Purchase Order Management", timeSaved: "12 hrs/week", difficulty: "medium" },
      { name: "Inventory Reconciliation", timeSaved: "15 hrs/week", difficulty: "hard" },
      { name: "Supplier Communication", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Production Reporting", timeSaved: "8 hrs/week", difficulty: "medium" },
      { name: "Quality Assurance Documents", timeSaved: "14 hrs/week", difficulty: "hard" },
      { name: "ERP Data Entry", timeSaved: "20 hrs/week", difficulty: "hard" },
      { name: "Bill of Materials Management", timeSaved: "6 hrs/week", difficulty: "medium" },
      { name: "Shipping Documentation", timeSaved: "8 hrs/week", difficulty: "easy" },
      { name: "Supplier Scorecards", timeSaved: "5 hrs/week", difficulty: "easy" },
      { name: "Material Requisition Processing", timeSaved: "7 hrs/week", difficulty: "easy" },
      { name: "Non-Conformance Reporting", timeSaved: "6 hrs/week", difficulty: "medium" },
      { name: "Preventive Maintenance Scheduling", timeSaved: "9 hrs/week", difficulty: "medium" },
      { name: "Job Cost Tracking", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Employee Time & Attendance", timeSaved: "8 hrs/week", difficulty: "easy" },
      { name: "Safety Incident Reporting", timeSaved: "4 hrs/week", difficulty: "easy" },
      { name: "Customer Order Processing", timeSaved: "12 hrs/week", difficulty: "medium" },
      { name: "RMA / Returns Processing", timeSaved: "7 hrs/week", difficulty: "medium" },
      { name: "Vendor Document Collection", timeSaved: "5 hrs/week", difficulty: "easy" },
      { name: "Production Schedule Communication", timeSaved: "6 hrs/week", difficulty: "easy" },
      { name: "Supplier Invoice Dispute Resolution", timeSaved: "8 hrs/week", difficulty: "hard" },
      { name: "Cycle Counting Coordination", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Engineering Change Notice Processing", timeSaved: "12 hrs/week", difficulty: "hard" },
      { name: "Export Documentation", timeSaved: "6 hrs/week", difficulty: "medium" },
      { name: "Environmental Reporting", timeSaved: "4 hrs/week", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 28,
      typicalHoursPerWeek: 40,
      implementationWeeks: 6,
      savingsMultiplier: 0.35,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "10 automations every manufacturer should deploy first",
      "ERP integration readiness checklist",
      "Supplier onboarding automation workflow",
      "Quality document automation step-by-step",
      "Production reporting setup guide",
    ],
    caseStudySnippets: [
      "Meridian Manufacturing reduced invoice processing from 11 minutes to 90 seconds per invoice, saving $340,000 annually across 3 facilities.",
      "A mid-market automotive parts supplier automated PO processing, cutting procurement cycle time from 3 days to 4 hours and achieving 98% on-time delivery.",
      "A food manufacturer deployed inventory reconciliation automation, improving accuracy from 84% to 99.7% and eliminating $2.1M in annual stockout losses.",
    ],
    commonIntegrations: ["SAP S/4HANA", "Oracle NetSuite", "Microsoft Dynamics 365", "Plex Systems", "QuickBooks Enterprise", "Epicor"],
    faqs: [
      { question: "How long does it take to deploy an AI Operations Team for manufacturing?", answer: "Most manufacturing clients see their first automation live within 2 weeks. Full deployment across all workflows typically completes in 6-8 weeks, with measurable ROI appearing in the first month." },
      { question: "Can the AI team work with our existing ERP system?", answer: "Yes. We connect directly to SAP, Oracle NetSuite, Dynamics 365, Epicor, Plex, and 25+ other manufacturing ERP systems through official APIs. No rip-and-replace required." },
      { question: "How does the system handle proprietary part numbers and BOM structures?", answer: "The AI Operations Team learns your specific data schemas during deployment. It maps your part numbering conventions, BOM hierarchies, and routing structures so every update is accurate and contextual." },
    ],
  },
  {
    id: "logistics",
    industry: ["logistics"],
    topAutomations: [
      { name: "Dispatch Scheduling Optimization", timeSaved: "25 hrs/week", difficulty: "hard" },
      { name: "Route Optimization", timeSaved: "18 hrs/week", difficulty: "hard" },
      { name: "Carrier Coordination & Rate Negotiation", timeSaved: "16 hrs/week", difficulty: "medium" },
      { name: "Proof of Delivery Collection", timeSaved: "12 hrs/week", difficulty: "easy" },
      { name: "Freight Invoice Audit", timeSaved: "20 hrs/week", difficulty: "hard" },
      { name: "LTL Manifesting & Rate Calculation", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Warehouse Inventory Sync", timeSaved: "14 hrs/week", difficulty: "medium" },
      { name: "Customer Rate Confirmation", timeSaved: "6 hrs/week", difficulty: "easy" },
      { name: "Driver HOS Compliance Tracking", timeSaved: "8 hrs/week", difficulty: "medium" },
      { name: "Load Tender & Acceptance", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Accessorial Charge Processing", timeSaved: "7 hrs/week", difficulty: "medium" },
      { name: "Customer POD Portal Updates", timeSaved: "5 hrs/week", difficulty: "easy" },
      { name: "Detention & Layover Billing", timeSaved: "8 hrs/week", difficulty: "easy" },
      { name: "Fleet Fuel Tax Reporting", timeSaved: "6 hrs/week", difficulty: "hard" },
      { name: "Driver Settlement Processing", timeSaved: "12 hrs/week", difficulty: "medium" },
      { name: "Customer Onboarding & Setup", timeSaved: "9 hrs/week", difficulty: "medium" },
      { name: "Rate Confirmation Auditing", timeSaved: "7 hrs/week", difficulty: "easy" },
      { name: "Cross-Dock Coordination", timeSaved: "8 hrs/week", difficulty: "hard" },
      { name: "Customer Claims Processing", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Interline Settlement Auditing", timeSaved: "6 hrs/week", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 26,
      typicalHoursPerWeek: 45,
      implementationWeeks: 8,
      savingsMultiplier: 0.40,
      breakEvenMonths: 4,
    },
    checklistTopics: [
      "Dispatch automation readiness checklist",
      "Freight audit automation setup guide",
      "Route optimization implementation steps",
      "Carrier onboarding automation workflow",
      "POD digital transformation checklist",
    ],
    caseStudySnippets: [
      "Coastline Logistics deployed dispatch automation and saw a single dispatcher handle 2.3x the shipment volume while on-time delivery improved from 84% to 97%.",
      "A regional LTL carrier automated freight invoice auditing, recovering 4.2% in overcharges ($620K annual) and reducing audit staffing needs by 60%.",
      "A national fleet implemented route optimization across 340 trucks, cutting fuel costs 12% and eliminating 340,000 excess miles in the first quarter.",
    ],
    commonIntegrations: ["McLeod Software", "MercuryGate TMS", "Trimble TMS", "Samsara", "Motive", "Project44", "DAT", "Truckstop"],
    faqs: [
      { question: "Can the AI team work with our existing TMS?", answer: "Yes. We integrate with McLeod, MercuryGate, Trimble, and 15+ other transportation management systems. The AI team reads dispatch boards, tracks loads, and updates your TMS automatically." },
      { question: "How does dispatch optimization actually work?", answer: "The AI team evaluates every available load against driver locations, HOS remaining, equipment compatibility, and customer appointment windows — generating an optimized plan in under 2 minutes that takes a human dispatcher 4+ hours." },
      { question: "What about broker-carrier communication?", answer: "The AI team handles load tendering, rate confirmation, status updates, and document exchange across email, EDI, and API — all without manual intervention." },
    ],
  },
  {
    id: "healthcare",
    industry: ["healthcare"],
    topAutomations: [
      { name: "Patient Intake & Registration", timeSaved: "22 hrs/week", difficulty: "medium" },
      { name: "Appointment Scheduling", timeSaved: "15 hrs/week", difficulty: "medium" },
      { name: "Insurance Verification", timeSaved: "18 hrs/week", difficulty: "medium" },
      { name: "Medical Coding Automation", timeSaved: "16 hrs/week", difficulty: "hard" },
      { name: "Claims Submission & Denial Management", timeSaved: "25 hrs/week", difficulty: "hard" },
      { name: "Compliance Reporting", timeSaved: "12 hrs/week", difficulty: "hard" },
      { name: "Patient Payment Collections", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Prior Authorization Processing", timeSaved: "14 hrs/week", difficulty: "hard" },
      { name: "Referral Management", timeSaved: "8 hrs/week", difficulty: "easy" },
      { name: "Medical Record Requests", timeSaved: "7 hrs/week", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 32,
      typicalHoursPerWeek: 40,
      implementationWeeks: 8,
      savingsMultiplier: 0.30,
      breakEvenMonths: 4,
    },
    checklistTopics: [
      "Revenue cycle automation checklist for healthcare",
      "Patient intake digitization guide",
      "Medical coding automation readiness",
      "Denial management improvement workflow",
      "HIPAA compliance automation checklist",
    ],
    caseStudySnippets: [
      "A 12-provider medical group automated insurance verification, reducing verification time from 8 minutes to 45 seconds per patient and cutting denial rates from 14% to 3%.",
      "A regional hospital deployed medical coding automation, achieving 97% coding accuracy and reducing the coding backlog from 14 days to 2 days.",
      "A multi-specialty practice automated claims processing, improving clean claim rate from 72% to 95% and reducing days in AR from 45 to 18.",
    ],
    commonIntegrations: ["Epic", "Cerner", "athenahealth", "NextGen", "Salesforce Health Cloud"],
    faqs: [
      { question: "Is the AI team HIPAA compliant?", answer: "Yes. All patient data is encrypted at rest and in transit. The system maintains BAA coverage, conducts annual SOC 2 audits, and never stores phi outside your secure environment." },
      { question: "Will this integrate with our EHR system?", answer: "We connect directly to Epic, Cerner, athenahealth, and NextGen through their official API and FHIR interfaces. No screen scraping or fragile integrations." },
    ],
  },
  {
    id: "construction",
    industry: ["construction"],
    topAutomations: [
      { name: "Submittal & Shop Drawing Review", timeSaved: "14 hrs/week", difficulty: "medium" },
      { name: "RFI Processing & Tracking", timeSaved: "8 hrs/week", difficulty: "easy" },
      { name: "Construction Timecard & Payroll", timeSaved: "18 hrs/week", difficulty: "medium" },
      { name: "Change Order Management", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Daily Field Report Automation", timeSaved: "6 hrs/week", difficulty: "easy" },
      { name: "Lien Waiver Processing", timeSaved: "5 hrs/week", difficulty: "easy" },
      { name: "Subcontractor Prequalification", timeSaved: "7 hrs/week", difficulty: "medium" },
      { name: "Equipment Tracking & Maintenance", timeSaved: "8 hrs/week", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 35,
      typicalHoursPerWeek: 45,
      implementationWeeks: 6,
      savingsMultiplier: 0.25,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "Top 5 construction workflows to automate first",
      "Submittal review automation guide",
      "Certified payroll compliance checklist",
      "Change order tracking best practices",
      "Field report digitization workflow",
    ],
    caseStudySnippets: [
      "A general contractor automated submittal review for a $47M hospital project, cutting review cycles from 21 to 8 days and reducing RFIs by 35%.",
      "A mid-size contractor deployed automated timecard and certified payroll processing, cutting payroll admin time 75% and eliminating prevailing wage compliance errors.",
    ],
    commonIntegrations: ["Procore", "Autodesk", "QuickBooks Enterprise", "Sage 50", "ADP"],
    faqs: [
      { question: "Does this work with Procore?", answer: "Yes. We integrate directly with Procore's API for submittals, RFIs, change orders, daily logs, and project financials." },
      { question: "Can it handle certified payroll requirements?", answer: "Yes. The AI team automatically calculates certified payroll for prevailing wage projects, generates Form WH-347 compliant reports, and tracks fringe benefit contributions." },
    ],
  },
  {
    id: "financial-services",
    industry: ["financial-services"],
    topAutomations: [
      { name: "AP Full Cycle Automation", timeSaved: "30 hrs/week", difficulty: "medium" },
      { name: "AR & Collections Automation", timeSaved: "20 hrs/week", difficulty: "medium" },
      { name: "Expense Report Automation", timeSaved: "12 hrs/week", difficulty: "easy" },
      { name: "Bank Reconciliation", timeSaved: "16 hrs/week", difficulty: "medium" },
      { name: "Budget vs Actual Tracking", timeSaved: "8 hrs/week", difficulty: "medium" },
      { name: "Financial Statement Preparation", timeSaved: "10 hrs/week", difficulty: "hard" },
      { name: "Intercompany Reconciliation", timeSaved: "14 hrs/week", difficulty: "hard" },
      { name: "Fixed Asset Tracking & Depreciation", timeSaved: "6 hrs/week", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 38,
      typicalHoursPerWeek: 40,
      implementationWeeks: 6,
      savingsMultiplier: 0.35,
      breakEvenMonths: 2,
    },
    checklistTopics: [
      "Finance department automation priority matrix",
      "AP automation implementation checklist",
      "Month-end close acceleration guide",
      "Expense policy automation setup",
      "Bank reconciliation automation workflow",
    ],
    caseStudySnippets: [
      "A regional bank automated AP processing across 14 branches, reducing invoice processing cost from $12.40 to $0.80 per invoice and accelerating month-end close by 5 days.",
      "A financial services firm deployed AR automation, reducing DSO from 47 to 28 days and improving collections efficiency by 300%.",
    ],
    commonIntegrations: ["QuickBooks", "Xero", "SAP", "Oracle NetSuite", "Bill.com", "Expensify", "Ramp", "Brex"],
    faqs: [
      { question: "Is this secure enough for financial services?", answer: "Yes. We maintain SOC 2 Type II certification, encrypt all data with AES-256, and support role-based access controls required for financial audits." },
      { question: "Can it handle multi-entity and multi-currency?", answer: "Yes. The AI team manages intercompany transactions, currency conversions, and consolidated reporting across entities and currencies automatically." },
    ],
  },
  {
    id: "energy",
    industry: ["energy"],
    topAutomations: [
      { name: "Well Production Reporting", timeSaved: "20 hrs/week", difficulty: "hard" },
      { name: "Environmental Compliance Monitoring", timeSaved: "16 hrs/week", difficulty: "hard" },
      { name: "Invoice & Royalty Processing", timeSaved: "24 hrs/week", difficulty: "hard" },
      { name: "Oilfield Supply Chain Automation", timeSaved: "14 hrs/week", difficulty: "medium" },
      { name: "Pipeline Monitoring & Alerts", timeSaved: "12 hrs/week", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 42,
      typicalHoursPerWeek: 45,
      implementationWeeks: 10,
      savingsMultiplier: 0.30,
      breakEvenMonths: 5,
    },
    checklistTopics: [
      "Production reporting automation guide",
      "Environmental compliance monitoring setup",
      "Revenue distribution automation workflow",
      "Supply chain optimization for oil & gas",
      "Regulatory filing automation checklist",
    ],
    caseStudySnippets: [
      "An independent operator with 47 wells automated production reporting, reducing report generation from 3 days to 20 minutes and identifying 3 underperforming wells for workover intervention.",
      "A midstream company deployed environmental compliance monitoring across 23 emission points, achieving 100% regulatory filing accuracy and reducing compliance event response time by 75%.",
    ],
    commonIntegrations: ["SAP", "Oracle NetSuite", "Power BI", "Tableau", "ServiceNow"],
    faqs: [
      { question: "Can the AI team handle division order calculations for royalty processing?", answer: "Yes. The system manages complex division of interest calculations, title chain updates, and burden deductions for any number of royalty owners." },
    ],
  },
  {
    id: "retail",
    industry: ["retail"],
    topAutomations: [
      { name: "Order Entry & Processing", timeSaved: "20 hrs/week", difficulty: "medium" },
      { name: "Multi-Channel Inventory Sync", timeSaved: "15 hrs/week", difficulty: "hard" },
      { name: "Customer Email Automation", timeSaved: "12 hrs/week", difficulty: "easy" },
      { name: "Returns & Refund Processing", timeSaved: "14 hrs/week", difficulty: "medium" },
      { name: "Vendor Onboarding & Compliance", timeSaved: "10 hrs/week", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 24,
      typicalHoursPerWeek: 40,
      implementationWeeks: 4,
      savingsMultiplier: 0.30,
      breakEvenMonths: 2,
    },
    checklistTopics: [
      "E-commerce order processing automation guide",
      "Inventory synchronization setup checklist",
      "Returns processing improvement workflow",
      "Vendor onboarding digitization",
      "Customer communication automation guide",
    ],
    caseStudySnippets: [
      "A multi-channel retailer automated order processing across 8 stores and 4 online channels, reducing processing time from 8 minutes to 30 seconds per order.",
      "An e-commerce brand deployed returns automation, cutting processing time from 7 days to 24 hours and improving customer satisfaction scores by 22%.",
    ],
    commonIntegrations: ["Shopify", "WooCommerce", "BigCommerce", "Amazon Seller Central", "NetSuite", "Fishbowl"],
    faqs: [
      { question: "Can this handle flash sales and high-volume periods?", answer: "Yes. The AI team scales automatically during peak periods. Black Friday volumes that would require 5 temporary staff are handled at normal capacity." },
    ],
  },
  {
    id: "legal",
    industry: ["legal"],
    topAutomations: [
      { name: "Contract Review & Analysis", timeSaved: "20 hrs/week", difficulty: "hard" },
      { name: "Client Intake & Conflict Check", timeSaved: "12 hrs/week", difficulty: "medium" },
      { name: "Docketing & Calendar Management", timeSaved: "8 hrs/week", difficulty: "hard" },
      { name: "Billable Time Entry", timeSaved: "10 hrs/week", difficulty: "medium" },
      { name: "Document Discovery & Review", timeSaved: "40 hrs/week", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 45,
      typicalHoursPerWeek: 45,
      implementationWeeks: 6,
      savingsMultiplier: 0.25,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "Law firm automation priority guide",
      "Contract review automation setup",
      "Conflict checking optimization workflow",
      "Time entry improvement checklist",
      "Discovery document processing guide",
    ],
    caseStudySnippets: [
      "A 50-attorney firm deployed contract review automation, reducing review time by 70% and increasing risk identification accuracy 3x over manual review.",
      "A litigation firm automated document discovery for a 500,000-document production, reducing review costs by 60% and completing the review in 3 weeks instead of 12.",
    ],
    commonIntegrations: ["Salesforce", "HubSpot", "SharePoint", "Adobe Sign", "Outlook"],
    faqs: [
      { question: "Does this comply with attorney-client privilege requirements?", answer: "Yes. The AI team is designed with privilege filter workflows, ethical wall controls, and complete audit trails for every document interaction." },
    ],
  },
  {
    id: "insurance",
    industry: ["insurance"],
    topAutomations: [
      { name: "Claims Intake & Triage", timeSaved: "18 hrs/week", difficulty: "medium" },
      { name: "Subrogation Recovery", timeSaved: "14 hrs/week", difficulty: "hard" },
      { name: "Policy Administration & Renewal", timeSaved: "16 hrs/week", difficulty: "medium" },
      { name: "Underwriting Data Gathering", timeSaved: "12 hrs/week", difficulty: "hard" },
      { name: "Claims Payment Processing", timeSaved: "15 hrs/week", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 30,
      typicalHoursPerWeek: 40,
      implementationWeeks: 8,
      savingsMultiplier: 0.30,
      breakEvenMonths: 4,
    },
    checklistTopics: [
      "Claims automation implementation guide",
      "Subrogation recovery optimization workflow",
      "Policy administration digitization checklist",
      "Underwriting support automation setup",
      "Compliance reporting automation guide",
    ],
    caseStudySnippets: [
      "A mid-market P&C insurer automated claims intake and triage, reducing FNOW processing from 4 hours to 15 minutes and achieving 94% accurate claim routing.",
      "An insurance carrier deployed subrogation automation, improving recovery rates from 34% to 52% and reducing the recovery cycle by 40%.",
    ],
    commonIntegrations: ["ServiceNow", "Salesforce", "HubSpot", "Outlook"],
    faqs: [
      { question: "How does the AI team handle complex claims with multiple policies?", answer: "The AI team evaluates all applicable policies, determines primary and excess coverage, calculates proportional liability, and generates comprehensive claim summaries for the adjuster." },
    ],
  },
  {
    id: "real-estate",
    industry: ["real-estate"],
    topAutomations: [
      { name: "Lease Document Processing", timeSaved: "16 hrs/week", difficulty: "hard" },
      { name: "Property Management Work Orders", timeSaved: "10 hrs/week", difficulty: "easy" },
      { name: "Rent Collection & Reconciliation", timeSaved: "14 hrs/week", difficulty: "medium" },
      { name: "Tenant Communication Automation", timeSaved: "6 hrs/week", difficulty: "easy" },
      { name: "Property Financial Reporting", timeSaved: "8 hrs/week", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 28,
      typicalHoursPerWeek: 40,
      implementationWeeks: 6,
      savingsMultiplier: 0.30,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "Property management automation priority guide",
      "Lease abstraction implementation checklist",
      "Rent collection automation workflow",
      "Tenant communication digitization guide",
      "ASC 842 compliance automation setup",
    ],
    caseStudySnippets: [
      "A commercial real estate firm with 1.2M sq ft deployed lease document processing, reducing abstraction time by 80% and achieving ASC 842 compliance with zero audit findings.",
      "A property management company automated work order processing across 2,400 units, reducing response time by 60% and maintenance costs by 15%.",
    ],
    commonIntegrations: ["QuickBooks", "Xero", "SAP", "NetSuite", "Adobe Sign", "Outlook"],
    faqs: [
      { question: "Can this handle ASC 842 lease accounting?", answer: "Yes. The AI team extracts all lease data needed for ASC 842 compliance, calculates right-of-use assets and lease liabilities, and generates journal entries for your ERP." },
    ],
  },
];