export interface IndustryResource {
  id: string;
  industry: string[];
  topAutomations: { name: string; timeSaved: string; difficulty: "easy" | "medium" | "hard" }[];
  roiCalculatorConfig: {
    avgHourlyRate: number;
    typicalHoursPerWeek: number;
    implementationWeeks: number;
    savingsMultiplier: number;
    breakEvenMonths: number;
  };
  checklistTopics: string[];
  commonIntegrations: string[];
  faqs: { question: string; answer: string }[];
}

export const industryResources: IndustryResource[] = [
  {
    id: "manufacturing",
    industry: ["manufacturing"],
    topAutomations: [
      { name: "Invoice Processing Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Purchase Order Management", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Inventory Reconciliation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Supplier Communication", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Production Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Quality Assurance Documents", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "ERP Data Entry", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Bill of Materials Management", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Shipping Documentation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Supplier Scorecards", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Material Requisition Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Non-Conformance Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Preventive Maintenance Scheduling", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Job Cost Tracking", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Employee Time & Attendance", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Safety Incident Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Customer Order Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "RMA / Returns Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Vendor Document Collection", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Production Schedule Communication", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Supplier Invoice Dispute Resolution", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Cycle Counting Coordination", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Engineering Change Notice Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Export Documentation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Environmental Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 28,
      typicalHoursPerWeek: 40,
      implementationWeeks: 6,
      savingsMultiplier: 0.35,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "10 automations every manufacturer should deploy first",
      "ERP integration readiness checklist",
      "Supplier onboarding automation workflow",
      "Quality document automation step-by-step",
      "Production reporting setup guide",
    ],
    commonIntegrations: ["SAP S/4HANA", "Oracle NetSuite", "Microsoft Dynamics 365", "Plex Systems", "QuickBooks Enterprise", "Epicor"],
    faqs: [
      { question: "How long does it take to get a manufacturing platform running?", answer: "Deployment timelines are scoped to each client's systems and processes rather than a fixed schedule. We outline expected timing and an illustrative ROI projection during your audit — actual results always depend on your specific operations." },
      { question: "Can the platform work with our existing ERP system?", answer: "Yes. We connect directly to SAP, Oracle NetSuite, Dynamics 365, Epicor, Plex, and 25+ other manufacturing ERP systems through official APIs. No rip-and-replace required." },
      { question: "How does the system handle proprietary part numbers and BOM structures?", answer: "The platform learns your specific data schemas during deployment. It maps your part numbering conventions, BOM hierarchies, and routing structures so every update is accurate and contextual." },
    ],
  },
  {
    id: "logistics",
    industry: ["logistics"],
    topAutomations: [
      { name: "Dispatch Scheduling Optimization", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Route Optimization", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Carrier Coordination & Rate Negotiation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Proof of Delivery Collection", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Freight Invoice Audit", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "LTL Manifesting & Rate Calculation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Warehouse Inventory Sync", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Customer Rate Confirmation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Driver HOS Compliance Tracking", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Load Tender & Acceptance", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Accessorial Charge Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Customer POD Portal Updates", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Detention & Layover Billing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Fleet Fuel Tax Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Driver Settlement Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Customer Onboarding & Setup", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Rate Confirmation Auditing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Cross-Dock Coordination", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Customer Claims Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Interline Settlement Auditing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 26,
      typicalHoursPerWeek: 45,
      implementationWeeks: 8,
      savingsMultiplier: 0.40,
      breakEvenMonths: 4,
    },
    checklistTopics: [
      "Dispatch automation readiness checklist",
      "Freight audit automation setup guide",
      "Route optimization implementation steps",
      "Carrier onboarding automation workflow",
      "POD digital transformation checklist",
    ],
    commonIntegrations: ["McLeod Software", "MercuryGate TMS", "Trimble TMS", "Samsara", "Motive", "Project44", "DAT", "Truckstop"],
    faqs: [
      { question: "Can the platform work with our existing TMS?", answer: "Yes. We integrate with McLeod, MercuryGate, Trimble, and 15+ other transportation management systems. The platform reads dispatch boards, tracks loads, and updates your TMS automatically." },
      { question: "How does dispatch optimization actually work?", answer: "The platform evaluates every available load against driver locations, HOS remaining, equipment compatibility, and customer appointment windows — generating an optimized plan in under 2 minutes that takes a human dispatcher 4+ hours." },
      { question: "What about broker-carrier communication?", answer: "The platform handles load tendering, rate confirmation, status updates, and document exchange across email, EDI, and API — all without manual intervention." },
    ],
  },
  {
    id: "healthcare",
    industry: ["healthcare"],
    topAutomations: [
      { name: "Patient Intake & Registration", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Appointment Scheduling", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Insurance Verification", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Medical Coding Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Claims Submission & Denial Management", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Compliance Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Patient Payment Collections", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Prior Authorization Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Referral Management", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Medical Record Requests", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 32,
      typicalHoursPerWeek: 40,
      implementationWeeks: 8,
      savingsMultiplier: 0.30,
      breakEvenMonths: 4,
    },
    checklistTopics: [
      "Revenue cycle automation checklist for healthcare",
      "Patient intake digitization guide",
      "Medical coding automation readiness",
      "Denial management improvement workflow",
      "HIPAA compliance automation checklist",
    ],
    commonIntegrations: ["Epic", "Cerner", "athenahealth", "NextGen", "Salesforce Health Cloud"],
    faqs: [
      { question: "Is the platform HIPAA compliant?", answer: "Yes. All patient data is encrypted at rest and in transit. We follow healthcare data-handling best practices, execute BAA coverage where applicable, and do not store PHI outside your secure environment." },
      { question: "Will this integrate with our EHR system?", answer: "We connect directly to Epic, Cerner, athenahealth, and NextGen through their official API and FHIR interfaces. No screen scraping or fragile integrations." },
    ],
  },
  {
    id: "construction",
    industry: ["construction"],
    topAutomations: [
      { name: "Submittal & Shop Drawing Review", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "RFI Processing & Tracking", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Construction Timecard & Payroll", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Change Order Management", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Daily Field Report Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Lien Waiver Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Subcontractor Prequalification", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Equipment Tracking & Maintenance", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 35,
      typicalHoursPerWeek: 45,
      implementationWeeks: 6,
      savingsMultiplier: 0.25,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "Top 5 construction workflows to automate first",
      "Submittal review automation guide",
      "Certified payroll compliance checklist",
      "Change order tracking best practices",
      "Field report digitization workflow",
    ],
    commonIntegrations: ["Procore", "Autodesk", "QuickBooks Enterprise", "Sage 50", "ADP"],
    faqs: [
      { question: "Does this work with Procore?", answer: "Yes. We integrate directly with Procore's API for submittals, RFIs, change orders, daily logs, and project financials." },
      { question: "Can it handle certified payroll requirements?", answer: "Yes. The platform automatically calculates certified payroll for prevailing wage projects, generates Form WH-347 compliant reports, and tracks fringe benefit contributions." },
    ],
  },
  {
    id: "financial-services",
    industry: ["financial-services"],
    topAutomations: [
      { name: "AP Full Cycle Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "AR & Collections Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Expense Report Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Bank Reconciliation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Budget vs Actual Tracking", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Financial Statement Preparation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Intercompany Reconciliation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Fixed Asset Tracking & Depreciation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 38,
      typicalHoursPerWeek: 40,
      implementationWeeks: 6,
      savingsMultiplier: 0.35,
      breakEvenMonths: 2,
    },
    checklistTopics: [
      "Finance department automation priority matrix",
      "AP automation implementation checklist",
      "Month-end close acceleration guide",
      "Expense policy automation setup",
      "Bank reconciliation automation workflow",
    ],
    commonIntegrations: ["QuickBooks", "Xero", "SAP", "Oracle NetSuite", "Bill.com", "Expensify", "Ramp", "Brex"],
    faqs: [
      { question: "Is this secure enough for financial services?", answer: "Yes. We follow information-security best practices, encrypt data in transit and at rest, and support role-based access controls required for financial audits." },
      { question: "Can it handle multi-entity and multi-currency?", answer: "Yes. The platform manages intercompany transactions, currency conversions, and consolidated reporting across entities and currencies automatically." },
    ],
  },
  {
    id: "energy",
    industry: ["energy"],
    topAutomations: [
      { name: "Well Production Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Environmental Compliance Monitoring", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Invoice & Royalty Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Oilfield Supply Chain Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Pipeline Monitoring & Alerts", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 42,
      typicalHoursPerWeek: 45,
      implementationWeeks: 10,
      savingsMultiplier: 0.30,
      breakEvenMonths: 5,
    },
    checklistTopics: [
      "Production reporting automation guide",
      "Environmental compliance monitoring setup",
      "Revenue distribution automation workflow",
      "Supply chain optimization for oil & gas",
      "Regulatory filing automation checklist",
    ],
    commonIntegrations: ["SAP", "Oracle NetSuite", "Power BI", "Tableau", "ServiceNow"],
    faqs: [
      { question: "Can the platform handle division order calculations for royalty processing?", answer: "Yes. The system manages complex division of interest calculations, title chain updates, and burden deductions for any number of royalty owners." },
    ],
  },
  {
    id: "retail",
    industry: ["retail"],
    topAutomations: [
      { name: "Order Entry & Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Multi-Channel Inventory Sync", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Customer Email Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Returns & Refund Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Vendor Onboarding & Compliance", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 24,
      typicalHoursPerWeek: 40,
      implementationWeeks: 4,
      savingsMultiplier: 0.30,
      breakEvenMonths: 2,
    },
    checklistTopics: [
      "E-commerce order processing automation guide",
      "Inventory synchronization setup checklist",
      "Returns processing improvement workflow",
      "Vendor onboarding digitization",
      "Customer communication automation guide",
    ],
    commonIntegrations: ["Shopify", "WooCommerce", "BigCommerce", "Amazon Seller Central", "NetSuite", "Fishbowl"],
    faqs: [
      { question: "Can this handle flash sales and high-volume periods?", answer: "Yes. The platform scales automatically during peak periods. Black Friday volumes that would require 5 temporary staff are handled at normal capacity." },
    ],
  },
  {
    id: "legal",
    industry: ["legal"],
    topAutomations: [
      { name: "Contract Review & Analysis", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Client Intake & Conflict Check", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Docketing & Calendar Management", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Billable Time Entry", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Document Discovery & Review", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 45,
      typicalHoursPerWeek: 45,
      implementationWeeks: 6,
      savingsMultiplier: 0.25,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "Law firm automation priority guide",
      "Contract review automation setup",
      "Conflict checking optimization workflow",
      "Time entry improvement checklist",
      "Discovery document processing guide",
    ],
    commonIntegrations: ["Salesforce", "HubSpot", "SharePoint", "Adobe Sign", "Outlook"],
    faqs: [
      { question: "Does this comply with attorney-client privilege requirements?", answer: "Yes. The platform is designed with privilege filter workflows, ethical wall controls, and complete audit trails for every document interaction." },
    ],
  },
  {
    id: "insurance",
    industry: ["insurance"],
    topAutomations: [
      { name: "Claims Intake & Triage", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Subrogation Recovery", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Policy Administration & Renewal", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Underwriting Data Gathering", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Claims Payment Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 30,
      typicalHoursPerWeek: 40,
      implementationWeeks: 8,
      savingsMultiplier: 0.30,
      breakEvenMonths: 4,
    },
    checklistTopics: [
      "Claims automation implementation guide",
      "Subrogation recovery optimization workflow",
      "Policy administration digitization checklist",
      "Underwriting support automation setup",
      "Compliance reporting automation guide",
    ],
    commonIntegrations: ["ServiceNow", "Salesforce", "HubSpot", "Outlook"],
    faqs: [
      { question: "How does the platform handle complex claims with multiple policies?", answer: "The platform evaluates all applicable policies, determines primary and excess coverage, calculates proportional liability, and generates comprehensive claim summaries for the adjuster." },
    ],
  },
  {
    id: "real-estate",
    industry: ["real-estate"],
    topAutomations: [
      { name: "Lease Document Processing", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "hard" },
      { name: "Property Management Work Orders", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Rent Collection & Reconciliation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
      { name: "Tenant Communication Automation", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "easy" },
      { name: "Property Financial Reporting", timeSaved: "Frees staff time spent on repetitive manual work", difficulty: "medium" },
    ],
    roiCalculatorConfig: {
      avgHourlyRate: 28,
      typicalHoursPerWeek: 40,
      implementationWeeks: 6,
      savingsMultiplier: 0.30,
      breakEvenMonths: 3,
    },
    checklistTopics: [
      "Property management automation priority guide",
      "Lease abstraction implementation checklist",
      "Rent collection automation workflow",
      "Tenant communication digitization guide",
      "ASC 842 compliance automation setup",
    ],
    commonIntegrations: ["QuickBooks", "Xero", "SAP", "NetSuite", "Adobe Sign", "Outlook"],
    faqs: [
      { question: "Can this handle ASC 842 lease accounting?", answer: "Yes. The platform extracts all lease data needed for ASC 842 compliance, calculates right-of-use assets and lease liabilities, and generates journal entries for your ERP." },
    ],
  },
];