export interface Integration {
  id: string;
  name: string;
  icon: string;
  category: "ERP" | "CRM" | "Finance" | "Communication" | "Cloud Storage" | "Industry Specific";
  description: string;
  capabilities: string[];
  industries: string[];
  relatedWorkflows: string[];
}

export const integrations: Integration[] = [
  {
    id: "sap",
    name: "SAP S/4HANA",
    icon: "sap",
    category: "ERP",
    description:
      "Deep integration with SAP S/4HANA for automated document processing, data synchronization, and workflow triggers across finance, procurement, manufacturing, and supply chain modules.",
    capabilities: [
      "Automated invoice posting and PO creation in SAP",
      "Real-time inventory and material master synchronization",
      "Automated production order creation and status updates",
      "Customer and vendor master data management",
      "Financial document posting with validation rules",
      "Automated FI/CO document creation and reconciliation",
    ],
    industries: ["manufacturing", "energy", "logistics", "retail", "construction"],
    relatedWorkflows: [
      "invoice-automation",
      "purchase-order-management",
      "inventory-reconciliation",
      "production-reporting",
      "erp-updates",
      "vendor-invoice-matching",
    ],
  },
  {
    id: "oracle-netsuite",
    name: "Oracle NetSuite",
    icon: "oracle-netsuite",
    category: "ERP",
    description:
      "Integrate with Oracle NetSuite to automate financial transactions, order management, procurement workflows, and reporting — eliminating manual data entry across modules.",
    capabilities: [
      "Automated sales order entry and fulfillment updates",
      "Purchase order creation and supplier invoice matching",
      "Inventory adjustments and location transfers",
      "Journal entry automation with custom segments",
      "Customer and vendor record creation and updates",
      "Saved search and report generation automation",
    ],
    industries: ["manufacturing", "retail", "logistics", "financial-services", "insurance"],
    relatedWorkflows: [
      "sales-order-processing",
      "purchase-order-management",
      "inventory-reconciliation",
      "erp-updates",
      "invoice-automation",
      "vendor-invoice-matching",
    ],
  },
  {
    id: "ms-dynamics-365",
    name: "Microsoft Dynamics 365",
    icon: "ms-dynamics-365",
    category: "ERP",
    description:
      "Connect with Dynamics 365 for automated data flows between sales, finance, supply chain, and operations — syncing records and triggering workflows.",
    capabilities: [
      "Automated lead-to-cash data synchronization",
      "Purchase order and invoice automation across modules",
      "Inventory transaction posting and reconciliation",
      "Project accounting and timesheet integration",
      "Customer engagement and marketing list updates",
      "Power Automate workflow trigger integration",
    ],
    industries: ["manufacturing", "retail", "financial-services", "construction", "energy"],
    relatedWorkflows: [
      "sales-order-processing",
      "invoice-automation",
      "inventory-reconciliation",
      "erp-updates",
      "purchase-order-management",
      "report-generation",
    ],
  },
  {
    id: "salesforce",
    name: "Salesforce",
    icon: "salesforce",
    category: "CRM",
    description:
      "Deep Salesforce integration for automated lead management, contact enrichment, opportunity tracking, case management, and workflow triggers.",
    capabilities: [
      "Automated lead creation and enrichment from emails and web forms",
      "Contact and account record updates from document data extraction",
      "Opportunity stage progression and task creation automation",
      "Case creation and routing from support inquiries",
      "Campaign member management and activity logging",
      "Custom object creation and field-level updates via API",
    ],
    industries: ["financial-services", "insurance", "real-estate", "legal", "healthcare", "retail"],
    relatedWorkflows: [
      "lead-response",
      "lead-scoring",
      "client-intake",
      "onboarding",
      "customer-support-triage",
      "report-generation",
      "customer-segmentation",
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    icon: "hubspot",
    category: "CRM",
    description:
      "Integrate with HubSpot for automated contact management, deal tracking, marketing automation triggers, and pipeline analytics.",
    capabilities: [
      "Automated contact creation and enrichment from email parsing",
      "Deal stage updates and task creation from document events",
      "Marketing list management and email campaign triggers",
      "Meeting scheduling automation from lead responses",
      "Custom property updates and association management",
      "Pipeline analytics and report generation automation",
    ],
    industries: ["real-estate", "financial-services", "insurance", "legal", "retail"],
    relatedWorkflows: [
      "lead-response",
      "lead-scoring",
      "client-intake",
      "email-management",
      "customer-segmentation",
      "report-generation",
    ],
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    icon: "quickbooks",
    category: "Finance",
    description:
      "Connect with QuickBooks Online and Desktop for automated invoice creation, expense categorization, payment reconciliation, and financial reporting.",
    capabilities: [
      "Automated invoice generation and email delivery",
      "Expense categorization from receipt data extraction",
      "Bank transaction matching and reconciliation",
      "Customer payment application to open invoices",
      "Vendor bill creation and payment scheduling",
      "Profit and loss report generation at configurable intervals",
    ],
    industries: ["manufacturing", "retail", "logistics", "construction", "real-estate", "insurance"],
    relatedWorkflows: [
      "invoice-automation",
      "ap-ar-automation",
      "payment-reconciliation",
      "expense-reporting",
      "invoice-reconciliation",
      "report-generation",
    ],
  },
  {
    id: "xero",
    name: "Xero",
    icon: "xero",
    category: "Finance",
    description:
      "Integrate with Xero for automated invoice processing, bank reconciliation, expense management, and multi-currency financial operations.",
    capabilities: [
      "Automated invoice creation and submission",
      "Bank feed import and transaction coding",
      "Expense claim processing and approval integration",
      "Multi-currency transaction handling and conversion",
      "Contact creation and updates from document data",
      "Financial report generation and dashboard updates",
    ],
    industries: ["retail", "financial-services", "real-estate", "logistics", "manufacturing"],
    relatedWorkflows: [
      "invoice-automation",
      "ap-ar-automation",
      "payment-reconciliation",
      "expense-reporting",
      "invoice-reconciliation",
    ],
  },
  {
    id: "ms-teams",
    name: "Microsoft Teams",
    icon: "ms-teams",
    category: "Communication",
    description:
      "Integrate AI agent notifications, approvals, and interactions directly into Microsoft Teams channels and chats for seamless team collaboration.",
    capabilities: [
      "Automated notification delivery to Teams channels",
      "Approval requests sent and processed within Teams",
      "Document sharing and preview within Teams conversations",
      "Bot-based Q&A and knowledge base access",
      "Meeting transcription and action item extraction",
      "Status updates and dashboard cards in Teams tabs",
    ],
    industries: ["manufacturing", "logistics", "healthcare", "financial-services", "insurance", "legal"],
    relatedWorkflows: [
      "report-generation",
      "email-management",
      "compliance-reporting",
      "service-desk-automation",
      "project-status-reporting",
    ],
  },
  {
    id: "slack",
    name: "Slack",
    icon: "slack",
    category: "Communication",
    description:
      "AI agent interactions, notifications, approvals, and updates delivered through Slack messages, channels, and workflows.",
    capabilities: [
      "Automated alerts and notifications to specific channels",
      "Approval workflows initiated and resolved in Slack",
      "Slash commands for agent queries and reporting",
      "Document previews and file sharing integration",
      "Workflow builder triggers for automated responses",
      "Status updates and real-time dashboard notifications",
    ],
    industries: ["manufacturing", "logistics", "retail", "financial-services", "technology", "insurance"],
    relatedWorkflows: [
      "report-generation",
      "email-management",
      "service-desk-automation",
      "customer-support-triage",
      "project-status-reporting",
    ],
  },
  {
    id: "outlook",
    name: "Microsoft Outlook",
    icon: "outlook",
    category: "Communication",
    description:
      "Monitor, triage, and respond to emails automatically within Outlook — extracting data, routing messages, and triggering workflows from email content.",
    capabilities: [
      "Email classification and auto-routing to departments",
      "Calendar event creation and meeting scheduling from emails",
      "Contact extraction and CRM record creation from email signatures",
      "Attachment processing: save, extract data, or route documents",
      "Automated reply generation for common inquiries",
      "Email thread analysis and conversation summarization",
    ],
    industries: ["manufacturing", "logistics", "healthcare", "financial-services", "legal", "insurance", "real-estate"],
    relatedWorkflows: [
      "email-management",
      "invoice-automation",
      "client-intake",
      "lead-response",
      "customer-support-triage",
      "document-processing",
    ],
  },
  {
    id: "gmail",
    name: "Gmail / Google Workspace",
    icon: "gmail",
    category: "Communication",
    description:
      "Integrate with Gmail and Google Workspace for email triage, data extraction, calendar management, and document processing across Google services.",
    capabilities: [
      "Email classification, routing, and automated responses",
      "Google Calendar event creation and meeting scheduling",
      "Contact extraction and Google Contacts updates",
      "Attachment processing and Google Drive storage",
      "Email thread analysis with conversation context tracking",
      "Automated label and folder organization based on rules",
    ],
    industries: ["manufacturing", "logistics", "healthcare", "real-estate", "legal", "financial-services"],
    relatedWorkflows: [
      "email-management",
      "invoice-automation",
      "lead-response",
      "client-intake",
      "document-processing",
      "appointment-scheduling",
    ],
  },
  {
    id: "google-drive",
    name: "Google Drive",
    icon: "google-drive",
    category: "Cloud Storage",
    description:
      "Monitor, organize, and process documents in Google Drive — automatically extracting data, categorizing files, and triggering workflows from new content.",
    capabilities: [
      "Document monitoring and ingestion from specified folders",
      "File categorization and auto-filing by type and content",
      "OCR processing of scanned documents stored in Drive",
      "Data extraction from spreadsheets, PDFs, and documents",
      "Template-based document generation and storage",
      "Permission management and sharing automation",
    ],
    industries: ["manufacturing", "logistics", "healthcare", "real-estate", "legal", "financial-services", "insurance"],
    relatedWorkflows: [
      "document-processing",
      "document-generation",
      "invoice-automation",
      "data-entry-automation",
      "compliance-reporting",
      "report-generation",
    ],
  },
  {
    id: "sharepoint",
    name: "Microsoft SharePoint",
    icon: "sharepoint",
    category: "Cloud Storage",
    description:
      "Integrate with SharePoint document libraries for automated document processing, metadata extraction, version control, and workflow integration.",
    capabilities: [
      "Document library monitoring and auto-classification",
      "Metadata extraction and custom column population",
      "Version control and approval workflow integration",
      "Document check-in/check-out automation",
      "Search-based document retrieval and organization",
      "Integration with Power Automate for extended workflows",
    ],
    industries: ["manufacturing", "energy", "financial-services", "legal", "insurance", "construction"],
    relatedWorkflows: [
      "document-processing",
      "document-generation",
      "compliance-reporting",
      "contract-review",
      "report-generation",
      "onboarding",
    ],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    icon: "dropbox",
    category: "Cloud Storage",
    description:
      "Monitor Dropbox folders for new documents, automatically process, classify, and route files to connected business systems.",
    capabilities: [
      "Folder monitoring and document ingestion",
      "File type classification and auto-routing",
      "OCR processing of images and scanned PDFs",
      "Document sharing and link generation automation",
      "Version history management and file recovery",
      "Cross-platform sync triggers for workflow automation",
    ],
    industries: ["legal", "real-estate", "financial-services", "insurance", "manufacturing"],
    relatedWorkflows: [
      "document-processing",
      "document-generation",
      "contract-review",
      "client-intake",
      "compliance-reporting",
    ],
  },
  {
    id: "onedrive",
    name: "Microsoft OneDrive",
    icon: "onedrive",
    category: "Cloud Storage",
    description:
      "Connect to OneDrive for automated document processing, file organization, and seamless integration with Microsoft 365 workflows.",
    capabilities: [
      "Automated file monitoring and ingestion from watched folders",
      "Document classification and metadata tagging",
      "Real-time file synchronization across devices",
      "Integration with Office 365 apps for document generation",
      "Version history tracking and file recovery",
      "Sharing and permission management automation",
    ],
    industries: ["manufacturing", "financial-services", "legal", "healthcare", "education"],
    relatedWorkflows: [
      "document-processing",
      "document-generation",
      "compliance-reporting",
      "onboarding",
      "report-generation",
    ],
  },
  {
    id: "box",
    name: "Box",
    icon: "box",
    category: "Cloud Storage",
    description:
      "Integrate with Box for secure document management, automated processing, and enterprise content collaboration.",
    capabilities: [
      "Document upload monitoring and auto-classification",
      "Metadata extraction and custom field population",
      "Content lifecycle management and retention policy enforcement",
      "Automated document sharing and collaboration invites",
      "Watermarking and security classification automation",
      "Workflow integration for document review and approval",
    ],
    industries: ["legal", "financial-services", "insurance", "healthcare", "energy"],
    relatedWorkflows: [
      "document-processing",
      "document-generation",
      "contract-review",
      "compliance-reporting",
      "client-intake",
    ],
  },
  {
    id: "s3",
    name: "Amazon S3",
    icon: "s3",
    category: "Cloud Storage",
    description:
      "Monitor S3 buckets for new files, process documents at scale, and trigger downstream workflows — ideal for high-volume document processing pipelines.",
    capabilities: [
      "S3 event notification listening (new file, modification)",
      "High-volume document ingestion and parallel processing",
      "Automated file categorization and storage optimization",
      "Data extraction and structured output to databases",
      "Lambda function triggers for custom processing logic",
      "Lifecycle policy integration and archive management",
    ],
    industries: ["manufacturing", "energy", "financial-services", "insurance", "logistics"],
    relatedWorkflows: [
      "document-processing",
      "data-entry-automation",
      "compliance-reporting",
      "report-generation",
      "invoice-automation",
    ],
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    icon: "servicenow",
    category: "Industry Specific",
    description:
      "Connect with ServiceNow for automated ticket creation, incident triage, change management, and IT service desk operations.",
    capabilities: [
      "Automated ticket creation from email, chat, and alerts",
      "Incident categorization, prioritization, and assignment",
      "Change request workflow automation and approval routing",
      "Knowledge base article suggestion and creation",
      "SLA monitoring and escalation automation",
      "CMDB record updates and configuration management",
    ],
    industries: ["financial-services", "healthcare", "manufacturing", "energy", "insurance", "technology"],
    relatedWorkflows: [
      "service-desk-automation",
      "customer-support-triage",
      "compliance-reporting",
      "onboarding",
      "email-management",
    ],
  },
  {
    id: "zendesk",
    name: "Zendesk",
    icon: "zendesk",
    category: "Industry Specific",
    description:
      "Integrate with Zendesk for automated ticket management, customer support triage, knowledge base integration, and customer satisfaction tracking.",
    capabilities: [
      "Automated ticket creation from email, chat, and web forms",
      "Ticket categorization, prioritization, and smart assignment",
      "Macro application and canned response automation",
      "Knowledge base article suggestion during ticket creation",
      "Customer satisfaction survey automation and analysis",
      "Ticket trend analysis and reporting",
    ],
    industries: ["retail", "financial-services", "insurance", "healthcare", "technology"],
    relatedWorkflows: [
      "customer-support-triage",
      "email-management",
      "customer-feedback-analysis",
      "report-generation",
      "lead-response",
    ],
  },
  {
    id: "workday",
    name: "Workday",
    icon: "workday",
    category: "Industry Specific",
    description:
      "Integrate with Workday for automated HR workflows, employee data management, payroll processing, and talent management operations.",
    capabilities: [
      "Employee record creation and updates from onboarding data",
      "Time tracking integration and payroll data feed",
      "Benefits enrollment and carrier file generation",
      "Performance review workflow automation",
      "Talent acquisition and applicant tracking integration",
      "Organizational reporting and workforce analytics",
    ],
    industries: ["financial-services", "healthcare", "manufacturing", "insurance", "retail"],
    relatedWorkflows: [
      "onboarding",
      "payroll-processing",
      "benefits-administration",
      "time-tracking",
      "recruitment-screening",
      "report-generation",
    ],
  },
  {
    id: "adp",
    name: "ADP",
    icon: "adp",
    category: "Industry Specific",
    description:
      "Connect with ADP Workforce Now and RUN for automated payroll data exchange, HRIS synchronization, and compliance reporting.",
    capabilities: [
      "Payroll data export and import automation",
      "Employee record synchronization with HRIS",
      "Time and attendance data feed to payroll",
      "Tax filing data preparation and submission",
      "Benefits enrollment data exchange with carriers",
      "Compliance reporting and new hire reporting",
    ],
    industries: ["manufacturing", "retail", "logistics", "financial-services", "insurance"],
    relatedWorkflows: [
      "payroll-processing",
      "onboarding",
      "benefits-administration",
      "time-tracking",
      "compliance-reporting",
    ],
  },
  {
    id: "epic",
    name: "Epic Systems",
    icon: "epic",
    category: "Industry Specific",
    description:
      "HIPAA-compliant integration with Epic EHR for automated patient data exchange, scheduling, billing, and clinical workflow support.",
    capabilities: [
      "Patient demographic data synchronization from intake forms",
      "Appointment scheduling and confirmation within Epic",
      "Insurance verification results integration into patient records",
      "Clinical note attachment and document management",
      "Charge capture and billing data integration",
      "Laboratory and radiology order processing automation",
    ],
    industries: ["healthcare"],
    relatedWorkflows: [
      "patient-intake",
      "appointment-scheduling",
      "insurance-verification",
      "medical-coding",
      "claims-processing",
      "document-processing",
    ],
  },
  {
    id: "cerner",
    name: "Cerner (Oracle Health)",
    icon: "cerner",
    category: "Industry Specific",
    description:
      "Integrate with Cerner EHR for automated patient data processing, clinical documentation, and revenue cycle management workflows.",
    capabilities: [
      "Patient registration and demographic data automation",
      "Clinical document attachment and classification",
      "Order entry and results processing automation",
      "Charge capture and billing workflow integration",
      "Appointment scheduling and no-show tracking",
      "Compliance and regulatory reporting data extraction",
    ],
    industries: ["healthcare"],
    relatedWorkflows: [
      "patient-intake",
      "appointment-scheduling",
      "insurance-verification",
      "medical-coding",
      "claims-processing",
      "compliance-reporting",
    ],
  },
  {
    id: "procore",
    name: "Procore",
    icon: "procore",
    category: "Industry Specific",
    description:
      "Connect with Procore for automated project management, document control, RFI tracking, and field reporting in construction operations.",
    capabilities: [
      "Project document upload and automated classification",
      "RFI creation, routing, and response tracking",
      "Submittal review workflow automation",
      "Daily log data collection and field report generation",
      "Change order creation and budget impact tracking",
      "Project status reporting and dashboard updates",
    ],
    industries: ["construction"],
    relatedWorkflows: [
      "document-processing",
      "project-status-reporting",
      "compliance-reporting",
      "invoice-automation",
      "purchase-order-management",
      "budget-tracking",
    ],
  },
  {
    id: "autocad",
    name: "AutoCAD / BIM 360",
    icon: "autocad",
    category: "Industry Specific",
    description:
      "Extract and process data from AutoCAD and BIM 360 drawings — automatically cataloging, versioning, and linking design data to project systems.",
    capabilities: [
      "Drawing file ingestion and metadata extraction",
      "Revision tracking and version control automation",
      "Title block data extraction for project linking",
      "Drawing set organization and naming standardization",
      "BIM 360 issue tracking and document association",
      "Design data export to project management systems",
    ],
    industries: ["construction", "manufacturing", "energy"],
    relatedWorkflows: [
      "document-processing",
      "data-entry-automation",
      "project-status-reporting",
      "compliance-reporting",
    ],
  },
  {
    id: "tableau",
    name: "Tableau",
    icon: "tableau",
    category: "Industry Specific",
    description:
      "Push processed data directly into Tableau data sources for automated dashboard updates, report generation, and executive analytics.",
    capabilities: [
      "Data source refresh automation from processed documents",
      "Dashboard data feed from workflow outputs",
      "Report generation triggers from data processing events",
      "Automated data extraction to Tableau extracts and Hyper files",
      "Embedded analytics integration for workflow dashboards",
      "Scheduled data push for daily/weekly report updates",
    ],
    industries: ["financial-services", "insurance", "retail", "manufacturing", "energy"],
    relatedWorkflows: [
      "report-generation",
      "compliance-reporting",
      "customer-segmentation",
      "budget-tracking",
      "customer-feedback-analysis",
    ],
  },
  {
    id: "power-bi",
    name: "Microsoft Power BI",
    icon: "power-bi",
    category: "Industry Specific",
    description:
      "Integrate with Power BI for automated report generation, dataset refresh, and dashboard publication from AI-processed data.",
    capabilities: [
      "Dataset refresh and data pipeline automation",
      "Dashboard publication from processed data flows",
      "Embedded report integration in workflow dashboards",
      "Automated data transformation and cleaning",
      "Scheduled report generation and distribution",
      "Real-time dashboard updates from streaming data",
    ],
    industries: ["financial-services", "insurance", "manufacturing", "retail", "energy"],
    relatedWorkflows: [
      "report-generation",
      "compliance-reporting",
      "budget-tracking",
      "customer-segmentation",
      "project-status-reporting",
    ],
  },
  {
    id: "jira",
    name: "Jira",
    icon: "jira",
    category: "Industry Specific",
    description:
      "Connect with Jira for automated issue creation, project tracking, sprint management, and development workflow integration.",
    capabilities: [
      "Automated issue creation from emails, forms, and alerts",
      "Issue field population and assignment automation",
      "Sprint planning data preparation and backlog management",
      "Release note generation from completed issues",
      "Time tracking integration with worklogs",
      "Project dashboard updates from issue data",
    ],
    industries: ["financial-services", "insurance", "manufacturing", "technology", "energy"],
    relatedWorkflows: [
      "project-status-reporting",
      "service-desk-automation",
      "report-generation",
      "time-tracking",
      "document-processing",
    ],
  },
  {
    id: "asana",
    name: "Asana",
    icon: "asana",
    category: "Industry Specific",
    description:
      "Integrate with Asana for automated task creation, project tracking, workflow automation, and team collaboration from AI-processed data.",
    capabilities: [
      "Task creation from emails, forms, and document processing events",
      "Task assignment and due date setting automation",
      "Project timeline updates and milestone tracking",
      "Portfolio reporting and status update automation",
      "Workflow rule triggers for recurring operations",
      "Team collaboration and approval request automation",
    ],
    industries: ["manufacturing", "construction", "financial-services", "legal", "real-estate"],
    relatedWorkflows: [
      "project-status-reporting",
      "onboarding",
      "report-generation",
      "compliance-reporting",
      "client-intake",
    ],
  },
];