export interface Workflow {
  id: string;
  name: string;
  industry: string[];
  description: string;
  painPoint: string;
  howItWorks: string[];
  timeSaved: string;
  accuracyGain: string;
  systemsRequired: string[];
  priceTier: "starter" | "growth" | "scale";
  roiTimeline: string;
}

export const workflows: Workflow[] = [
  {
    id: "invoice-automation",
    name: "Invoice Processing Automation",
    industry: ["manufacturing", "logistics", "construction", "retail", "energy", "financial-services", "insurance", "legal"],
    description:
      "Extract, validate, and post invoices from any format — PDF, scanned image, email attachment, EDI — directly into your ERP or accounting system without manual data entry.",
    painPoint:
      "Accounts payable teams manually open each invoice, type vendor details and line items into the ERP, match against purchase orders, and route for approval. A single invoice takes 8-12 minutes of keystrokes, and typos cause payment delays and vendor disputes.",
    howItWorks: [
      "Agent monitors email inbox, document upload folder, and EDI queue for new invoices",
      "Extracts vendor name, invoice number, date, line items, quantities, unit prices, and totals using OCR + LLM validation",
      "Cross-references line items against matching POs and receiving documents in the ERP",
      "Flags mismatches (price, quantity, or missing PO) for human review with a side-by-side comparison",
      "Categorizes by GL code, cost center, and project based on ERP mapping rules",
      "Routes approved invoices to the payment queue and posts them to the ERP",
    ],
    timeSaved: "85% reduction in invoice processing time — from 10 minutes to 90 seconds per invoice",
    accuracyGain: "99.7% data extraction accuracy — eliminates typos and transposition errors",
    systemsRequired: ["ERP/Accounting system", "Email inbox", "Document storage (SharePoint, Google Drive)"],
    priceTier: "starter",
    roiTimeline: "3-4 weeks",
  },
  {
    id: "purchase-order-management",
    name: "Purchase Order Management",
    industry: ["manufacturing", "logistics", "construction", "retail", "energy"],
    description:
      "Generate, approve, and track purchase orders from requisition through delivery. Automate PO creation from reorder points, budget checks, and supplier matching.",
    painPoint:
      "Procurement teams manually create POs from requisition emails, check budgets in spreadsheets, email suppliers for quotes, and track delivery status via phone. A single PO cycle takes 30+ minutes of back-and-forth.",
    howItWorks: [
      "Agent monitors inventory levels, reorder points, and requisition requests across systems",
      "Generates POs based on configured reorder rules, minimum quantities, and preferred supplier lists",
      "Checks remaining budget in the ERP against PO total and flags over-budget items for approval",
      "Sends PO to supplier via email or EDI and tracks acknowledgment",
      "Monitors delivery status against scheduled dates and escalates delays",
      "Reconciles received quantities against PO on delivery, triggering payment or backorder processes",
    ],
    timeSaved: "70% reduction in PO cycle time — from 30+ minutes to under 5 minutes per order",
    accuracyGain: "100% PO-to-requisition matching — no more data entry errors",
    systemsRequired: ["ERP", "Inventory management system", "Email"],
    priceTier: "starter",
    roiTimeline: "4-6 weeks",
  },
  {
    id: "inventory-reconciliation",
    name: "Inventory Reconciliation",
    industry: ["manufacturing", "retail", "logistics", "energy", "healthcare"],
    description:
      "Automatically reconcile inventory counts across systems — raw materials, WIP, finished goods, and warehouse locations — identifying discrepancies in real time.",
    painPoint:
      "Inventory data lives in disconnected systems: WMS, ERP, spreadsheets, and physical counts. Reconciliation requires manually exporting data from each system, aligning SKUs, and hunting for discrepancies. Teams spend 15+ hours weekly on this cycle.",
    howItWorks: [
      "Agent connects to WMS, ERP, and any inventory spreadsheets via API or file import",
      "Pulls current stock levels, location data, and recent movements from each source",
      "Aligns SKU mappings across systems (handles different naming conventions)",
      "Identifies discrepancies: missing items, excess quantities, location mismatches",
      "Categorizes discrepancies by severity, root cause, and financial impact",
      "Generates reconciliation report with recommended adjustment journal entries",
    ],
    timeSaved: "90% reduction in reconciliation time — from 15 hours to under 2 hours weekly",
    accuracyGain: "99.9% inventory accuracy — discrepancies caught within hours instead of weeks",
    systemsRequired: ["ERP or WMS", "Inventory management system"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "supplier-communication",
    name: "Supplier Communication Automation",
    industry: ["manufacturing", "logistics", "construction", "retail", "energy"],
    description:
      "Automate supplier outreach — RFQs, order acknowledgments, delivery status checks, quality issue notifications — via email or EDI, with intelligent response handling.",
    painPoint:
      "Procurement teams spend hours each day emailing suppliers for quotes, delivery updates, and issue resolution. Each supplier interaction requires tracking a separate email thread, and urgent requests get lost in overflowing inboxes.",
    howItWorks: [
      "Agent analyzes incoming supplier emails and categorizes them by intent (quote request, delivery update, issue report)",
      "Generates and sends RFQs to suppliers based on configured product lists and quantities",
      "Monitors supplier responses, extracts quote details, and populates a comparison table",
      "Sends automated order acknowledgments and delivery schedule confirmations",
      "Detects delivery delays or quality issues in supplier communications and escalates with context",
      "Maintains a searchable log of all supplier interactions for audit and dispute resolution",
    ],
    timeSaved: "75% reduction in supplier communication time — from 4+ hours to under 1 hour daily",
    accuracyGain: "100% capture of supplier commitments and delivery promises",
    systemsRequired: ["Email", "ERP or procurement system"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "production-reporting",
    name: "Production Reporting",
    industry: ["manufacturing", "energy", "construction"],
    description:
      "Digitize shop floor and field production data — automatically collect output counts, downtime events, yield rates, and quality metrics from equipment PLCs, operator inputs, and inspection stations.",
    painPoint:
      "Production data is collected on paper logs, whiteboards, and operator terminals. Supervisors spend 2+ hours per shift consolidating reports into spreadsheets. By the time management sees production numbers, they're a full day behind.",
    howItWorks: [
      "Agent ingests data from PLCs, SCADA systems, operator terminals, and manual entry forms",
      "Calculates OEE metrics: availability, performance, quality in real time",
      "Flags downtime events and production stoppages with root cause tags",
      "Generates shift reports, daily production summaries, and weekly trend analyses",
      "Pushes production data to ERP for cost roll-up and inventory valuation",
      "Sends alerts when production falls below target thresholds",
    ],
    timeSaved: "80% faster production reporting — from 2+ hours per shift to real-time automated dashboards",
    accuracyGain: "100% accurate production counts — no more manual tally errors or missing entries",
    systemsRequired: ["ERP or MES", "PLC/SCADA connectivity or manual entry interface"],
    priceTier: "growth",
    roiTimeline: "6-10 weeks",
  },
  {
    id: "quality-assurance",
    name: "Quality Assurance Documentation",
    industry: ["manufacturing", "energy", "healthcare", "construction"],
    description:
      "Automate QA documentation — inspection checklists, non-conformance reports, corrective action tracking, and certificate of analysis generation.",
    painPoint:
      "QA teams manually fill inspection checklists, type non-conformance reports, and compile certificates of analysis. Each inspection generates 30 minutes of paperwork. Non-conformance reports take 2+ hours to write and route for corrective action.",
    howItWorks: [
      "Agent presents digital inspection checklists on tablets or web forms with pre-populated specs",
      "Validates inspection results against tolerance ranges, flagging out-of-spec readings immediately",
      "Generates non-conformance reports with photo attachments, root cause codes, and corrective action assignments",
      "Tracks corrective actions through resolution and verifies effectiveness with re-inspection data",
      "Creates certificates of analysis automatically from passed inspection data",
      "Maintains searchable QA record database for audits and customer inquiries",
    ],
    timeSaved: "60% reduction in QA documentation time — saves 12+ hours per inspector weekly",
    accuracyGain: "100% inspection data capture — no more lost paper forms or transcription errors",
    systemsRequired: ["Quality management system or ERP", "Tablets or web forms for data entry"],
    priceTier: "growth",
    roiTimeline: "6-10 weeks",
  },
  {
    id: "erp-updates",
    name: "ERP Data Synchronization",
    industry: ["manufacturing", "logistics", "energy", "retail", "construction"],
    description:
      "Automatically update ERP records from external data sources — production output, inventory movements, supplier invoices, customer orders — without manual data entry.",
    painPoint:
      "Data flows into the ERP from multiple sources — production systems, supplier portals, customer emails, and spreadsheets. Each source requires someone to manually type or copy-paste data into the ERP. Data is always 1-3 days behind reality.",
    howItWorks: [
      "Agent connects to external data sources via API, file import, email parsing, or web scraping",
      "Validates incoming data against ERP schema and business rules before posting",
      "Creates or updates ERP records: POs, sales orders, inventory transactions, production orders, journal entries",
      "Handles exceptions and validation failures with clear error messages for human review",
      "Maintains an audit log of every change made to the ERP, with source traceability",
      "Runs on a configurable schedule — real-time, hourly, daily — matching business requirements",
    ],
    timeSaved: "95% reduction in manual ERP data entry — thousands of keystrokes eliminated daily",
    accuracyGain: "99.8% data accuracy with full audit trail for every transaction",
    systemsRequired: ["ERP system with API access"],
    priceTier: "scale",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "dispatch-scheduling",
    name: "Dispatch Scheduling",
    industry: ["logistics"],
    description:
      "Intelligently assign loads to drivers and equipment based on capacity, location, driver hours, customer preferences, and delivery windows — with real-time re-optimization.",
    painPoint:
      "Dispatchers manually assign loads each morning using whiteboards, spreadsheets, and phone calls. Each assignment requires checking driver availability, hours of service, equipment type, and customer preferences. A single change cascades into 30 minutes of re-planning.",
    howItWorks: [
      "Agent pulls inbound loads from TMS or customer orders, along with driver status, equipment availability, and HOS logs",
      "Creates optimized route and driver assignments considering delivery windows, weight limits, and customer preferences",
      "Generates dispatch manifests and sends them to driver mobile apps or email",
      "Monitors real-time traffic, weather, and driver status, re-routing proactively",
      "Handles last-minute changes — breakdowns, cancellations, new pickups — with rapid re-optimization",
      "Tracks dispatch-to-delivery cycle time and dispatcher productivity metrics",
    ],
    timeSaved: "70% reduction in dispatch scheduling time — from 3+ hours to under 1 hour daily",
    accuracyGain: "98% on-time dispatch rate vs 82% manual baseline",
    systemsRequired: ["TMS or order management system", "Driver mobile app or SMS gateway"],
    priceTier: "growth",
    roiTimeline: "6-10 weeks",
  },
  {
    id: "route-optimization",
    name: "Route Optimization",
    industry: ["logistics"],
    description:
      "Continuously optimize delivery and service routes based on real-time traffic, order windows, vehicle capacity, driver hours, and customer preferences.",
    painPoint:
      "Routes are planned manually once in the morning and locked for the day. Traffic jams, road closures, and new pickup requests cause cascading delays. Fuel costs are 15-20% higher than necessary due to suboptimal routing.",
    howItWorks: [
      "Agent ingests all stops for the day with time windows, service durations, and priority levels",
      "Factors in vehicle capacity, driver hours of service, and equipment restrictions",
      "Produces optimized stop sequences using multi-variable routing algorithms",
      "Sends optimized routes to driver mobile apps with turn-by-turn directions",
      "Monitors real-time conditions and re-optimizes routes dynamically when delays or new stops arise",
      "Tracks planned vs actual route performance and identifies improvement opportunities",
    ],
    timeSaved: "80% less time spent on route planning — from 90 minutes to under 15 minutes daily",
    accuracyGain: "22% reduction in fuel costs and 15% improvement in stops-per-hour",
    systemsRequired: ["TMS or dispatch system", "Driver mobile app or GPS tracking integration"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "carrier-coordination",
    name: "Carrier Coordination",
    industry: ["logistics"],
    description:
      "Automate carrier rate requests, booking confirmations, status updates, document exchange, and payment reconciliation across multiple carriers.",
    painPoint:
      "Logistics coordinators manage 20+ carriers via separate phone calls, emails, and portals. Rate requests take 30 minutes of calling around. Booking confirmations arrive in PDF attachments that must be manually filed. Status updates require calling individual dispatchers.",
    howItWorks: [
      "Agent sends rate requests to carriers via email, API, or load board integration based on shipment specifications",
      "Collects and compares carrier responses, presenting a ranked view by price, transit time, and reliability score",
      "Books shipments with selected carriers and sends confirmation with pickup details, BOL, and special instructions",
      "Monitors carrier performance metrics: on-time pickup, on-time delivery, claims ratio, and communication responsiveness",
      "Collects and files carrier documents: rate confirmations, BOLs, PODs, and invoices",
      "Reconciles carrier invoices against booked rates and flags discrepancies for resolution",
    ],
    timeSaved: "65% reduction in carrier coordination time — from 5+ hours to under 2 hours daily",
    accuracyGain: "100% rate confirmation capture with searchable carrier communication history",
    systemsRequired: ["Email", "TMS or load board access", "Rate database or carrier portal access"],
    priceTier: "growth",
    roiTimeline: "6-10 weeks",
  },
  {
    id: "pod-collection",
    name: "Proof of Delivery Collection & Matching",
    industry: ["logistics"],
    description:
      "Automatically collect, digitize, and match proof-of-delivery documents — signatures, photos, timestamps — to shipments and invoices.",
    painPoint:
      "Drivers collect paper signatures on delivery receipts that get lost, faded, or stuck in truck cabs for days. Without PODs, invoices can't be sent. Disputes over delivery confirmation pile up, and carriers withhold payment until PODs are submitted.",
    howItWorks: [
      "Agent ingests PODs from driver mobile app, email attachments, or scanned uploads",
      "Extracts signature, delivery timestamp, recipient name, and photos using OCR and image analysis",
      "Matches each POD to the corresponding shipment record using BOL number, date, and delivery address",
      "Flags missing or illegible PODs and sends automated reminders to drivers",
      "Files matched PODs in the document management system linked to the invoice",
      "Tracks POD completion rate by driver, route, and customer for performance monitoring",
    ],
    timeSaved: "90% faster POD processing — from 3+ days to same-day invoice-ready matching",
    accuracyGain: "99.5% POD-to-shipment match rate with searchable document archive",
    systemsRequired: ["Driver mobile app or camera", "TMS or order management system", "Document storage"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "freight-audit",
    name: "Freight Invoice Audit",
    industry: ["logistics", "manufacturing", "retail"],
    description:
      "Automatically audit freight invoices against contracted rates, accessorial charges, and delivery receipts — flagging overcharges for recovery.",
    painPoint:
      "Carriers send thousands of freight invoices monthly in different formats. AP teams manually check rates against contracts, verify accessorial charges, and confirm delivery. Studies show 3-7% of freight charges contain errors, but most go uncaught because manual audit is too slow.",
    howItWorks: [
      "Agent ingests freight invoices from email, EDI, or carrier portals",
      "Extracts charges, line items, accessorials, and reference numbers from each invoice",
      "Matches each invoice against contracted rates, customer-specific pricing, and rate confirmations",
      "Validates accessorial charges against delivery circumstances and contract terms",
      "Flags overcharges, duplicate invoices, and billing errors with calculated recovery amounts",
      "Generates dispute letters and credit request forms for flagged items",
    ],
    timeSaved: "85% faster freight audit cycle — from 45 minutes per invoice to under 5 minutes",
    accuracyGain: "3-7% freight cost recovery that would otherwise be missed — pure bottom-line savings",
    systemsRequired: ["ERP or accounting system", "Carrier rate database or contract repository", "Email"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "patient-intake",
    name: "Patient Intake Automation",
    industry: ["healthcare"],
    description:
      "Digitize and automate patient registration — from form collection through demographic entry, insurance verification, and EHR record creation.",
    painPoint:
      "Patients fill paper forms in the waiting room. Staff manually transcribe handwritten data into the EHR, verify insurance by phone, and scan documents into a folder. Each new patient takes 15-20 minutes of manual processing. Errors in demographic entry cause billing rejections months later.",
    howItWorks: [
      "Agent sends digital intake forms to patients via text or email before their appointment",
      "Extracts patient demographics, insurance info, medical history, and consent from completed forms using OCR + LLM",
      "Verifies insurance eligibility via payer API or web portal, capturing copay, deductible, and coverage details",
      "Creates the patient record in the EHR with all verified information and document attachments",
      "Notifies staff of any missing information or insurance issues before the appointment",
      "Collects copay estimates and sends pre-visit payment requests when applicable",
    ],
    timeSaved: "80% reduction in intake processing time — from 20 minutes to under 3 minutes per patient",
    accuracyGain: "99.9% demographic accuracy — eliminates billing rejections from data entry errors",
    systemsRequired: ["EHR system", "Insurance verification API or portal access", "Email/SMS gateway"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "appointment-scheduling",
    name: "Appointment Scheduling & Reminders",
    industry: ["healthcare", "real-estate", "legal", "financial-services"],
    description:
      "Automate appointment booking, rescheduling, reminders, and waitlist management across providers, locations, and time zones.",
    painPoint:
      "Front desk staff spend 30+ hours weekly on phone-based scheduling. Each appointment requires 3-5 minutes of conversation, plus insurance verification and appointment confirmation. No-show rates of 15-30% persist because manual reminder calls are skipped during busy periods.",
    howItWorks: [
      "Agent provides self-service booking links via text, email, or web widget with real-time availability",
      "Synchronizes booked appointments across provider calendars, locations, and time zones",
      "Sends automated reminders via text and email at configured intervals (72h, 24h, 2h before)",
      "Handles rescheduling and cancellations via reply-to-text or self-service link",
      "Manages waitlists by automatically offering available slots to next-in-line patients",
      "Tracks no-show patterns and adjusts reminder frequency or type based on patient history",
    ],
    timeSaved: "90% reduction in phone-based scheduling time — saves 25+ front desk hours weekly",
    accuracyGain: "94% show rate achieved — 4x improvement over manual reminder processes",
    systemsRequired: ["Calendar system (Google, Outlook)", "EHR or practice management system", "SMS/Email gateway"],
    priceTier: "starter",
    roiTimeline: "2-3 weeks",
  },
  {
    id: "insurance-verification",
    name: "Insurance Verification",
    industry: ["healthcare", "insurance"],
    description:
      "Automate patient insurance eligibility checks, benefits verification, and pre-authorization status across payers and plans.",
    painPoint:
      "Front office staff spend 8-12 minutes per patient on insurance verification by phone or payer portal. Each verification involves waiting on hold, navigating payer IVR systems, and manually entering data. Patients show up for appointments only to discover their insurance is inactive.",
    howItWorks: [
      "Agent receives patient insurance details from intake forms or EHR",
      "Queries payer eligibility APIs or logs into payer portals to verify active coverage",
      "Captures benefits details: copay, deductible, coinsurance, out-of-pocket max, and coverage limitations",
      "Checks pre-authorization requirements and flags services needing prior auth",
      "Records verification results in the EHR with timestamps and payer confirmation numbers",
      "Sends alerts when coverage issues are detected, allowing pre-appointment resolution",
    ],
    timeSaved: "75% reduction in verification time — from 10 minutes to under 2 minutes per patient",
    accuracyGain: "100% verification documentation — eliminates he-said-she-said with payers",
    systemsRequired: ["EHR or practice management system", "Payer API or portal access"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "medical-coding",
    name: "Medical Coding Assistance",
    industry: ["healthcare"],
    description:
      "Analyze clinical documentation to suggest accurate ICD-10, CPT, and HCPCS codes, reducing coding backlog and denial rates.",
    painPoint:
      "Clinicians dictate notes that sit in a queue for medical coders. Each record takes 8-15 minutes to code. Backlogs of 3-5 days delay billing cycles. Coding errors cause claim denials that take another 30 days to resubmit.",
    howItWorks: [
      "Agent extracts clinical details from physician notes, lab results, and procedure reports",
      "Suggests ICD-10 diagnosis codes and CPT/HCPCS procedure codes based on documentation",
      "Flags documentation gaps that would lead to coding denials or queries",
      "Validates code combinations against payer-specific medical necessity rules",
      "Presents suggested codes for coder review and approval with supporting evidence",
      "Tracks coding accuracy and denial patterns to continuously improve suggestions",
    ],
    timeSaved: "50% faster coding cycle — from 10 minutes to under 5 minutes per record",
    accuracyGain: "30% reduction in coding-related claim denials",
    systemsRequired: ["EHR with clinical notes", "Medical coding software or encoder"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "claims-processing",
    name: "Claims Processing",
    industry: ["healthcare", "insurance"],
    description:
      "Automate claims intake, validation, adjudication, and payment processing — from first submission through final settlement or denial.",
    painPoint:
      "Claims arrive in multiple formats — electronic, paper, email — and each requires manual validation against policy terms, coverage limits, and medical necessity rules. Processing a single claim takes 15-25 minutes. Backlogs stretch to 30+ days during peak periods.",
    howItWorks: [
      "Agent ingests claims from EDI feeds, payer portals, email attachments, and paper scans",
      "Validates claim completeness: member info, provider details, diagnosis codes, procedure codes, charges",
      "Checks eligibility, benefits, and pre-authorization against policy data",
      "Applies adjudication rules: deductible, copay, coinsurance, out-of-pocket maximum, bundling logic",
      "Calculates allowed amount, patient responsibility, and provider payment",
      "Generates explanation of benefits, claim status responses, and payment instructions",
    ],
    timeSaved: "80% faster claims processing — from 20 minutes to under 4 minutes per claim",
    accuracyGain: "95% first-pass adjudication rate vs 65% industry average",
    systemsRequired: ["Claims management system", "Policy administration system", "Eligibility data source"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "compliance-reporting",
    name: "Compliance Reporting",
    industry: [
      "financial-services",
      "healthcare",
      "energy",
      "insurance",
      "manufacturing",
      "legal",
      "construction",
    ],
    description:
      "Automate regulatory reporting — collect evidence, map controls to requirements, generate filing documents, and maintain audit trails.",
    painPoint:
      "Compliance teams spend 2-4 weeks per quarter manually collecting evidence for regulatory filings. Data must be pulled from 4+ systems, normalized into spreadsheets, and formatted for each regulator. Exam preparation consumes hundreds of person-hours every cycle.",
    howItWorks: [
      "Agent maps regulatory requirements to internal controls, policies, and procedures",
      "Collects evidence from connected systems: access logs, policy acknowledgments, training records, incident reports",
      "Validates evidence against control descriptions and flags gaps for remediation",
      "Generates audit-ready evidence packages with timestamps, system source tags, and responsible parties",
      "Formats reports for each regulator's required submission format",
      "Maintains continuous compliance posture dashboard with real-time control status",
    ],
    timeSaved: "80% reduction in reporting preparation time — from weeks to days",
    accuracyGain: "100% audit pass rate with complete, timestamped evidence packages",
    systemsRequired: ["Compliance management system", "Identity and access management logs", "HR system"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "ap-ar-automation",
    name: "Accounts Payable & Receivable Automation",
    industry: ["financial-services", "retail", "insurance", "legal", "real-estate", "manufacturing"],
    description:
      "Automate end-to-end AP and AR workflows — invoice capture, approval routing, payment scheduling, collections, and reconciliation.",
    painPoint:
      "Finance teams manage AP and AR through separate systems, spreadsheets, and email threads. Invoices get stuck in approval queues. Payment runs require manual data extraction and upload. Collections follow-ups happen once a month at best. Cash flow visibility is always 2 weeks behind.",
    howItWorks: [
      "Agent captures invoices from email, document uploads, and EDI feeds, routing them through configurable approval workflows",
      "Schedules payments based on terms, discount opportunities, and cash position",
      "Generates customer invoices and sends them with payment links via email or portal",
      "Tracks payment status and sends automated reminders at configurable intervals (3 days, 7 days, 15 days overdue)",
      "Reconciles payments received against invoices and bank deposits, flagging short-pays and over-pays",
      "Generates aging reports, cash flow forecasts, and DSO/DPO metrics",
    ],
    timeSaved: "75% reduction in AP/AR processing time — saves 20+ finance hours weekly",
    accuracyGain: "99.5% reconciliation accuracy with complete audit trail",
    systemsRequired: ["Accounting or ERP system", "Bank account access or payment processor", "Email"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "data-entry-automation",
    name: "Data Entry Automation",
    industry: [
      "manufacturing",
      "logistics",
      "healthcare",
      "construction",
      "financial-services",
      "energy",
      "retail",
      "legal",
      "insurance",
      "real-estate",
    ],
    description:
      "Extract structured data from any source — emails, PDFs, scanned documents, web pages, spreadsheets — and enter it into your systems without manual keystrokes.",
    painPoint:
      "Every department has data entry: customer details from emails into CRM, supplier info from PDFs into ERP, patient data from forms into EHR. Data entry consumes 15-30% of administrative work hours across organizations and produces chronic accuracy problems.",
    howItWorks: [
      "Agent monitors configured data sources: email inbox, document uploads, webhooks, API endpoints",
      "Extracts relevant fields using OCR, document parsing, and LLM understanding",
      "Validates extracted data against business rules: format checks, range validation, cross-field consistency",
      "Enters data into target systems via API or robotic process automation",
      "Flags ambiguous or low-confidence extractions for human verification",
      "Maintains an audit log of every data entry with source document traceability",
    ],
    timeSaved: "95% reduction in manual data entry — thousands of keystrokes eliminated per day",
    accuracyGain: "99.7% data accuracy, eliminating downstream errors from typos and transpositions",
    systemsRequired: ["Target system (CRM, ERP, EHR) with API", "Email or document source"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "document-processing",
    name: "Intelligent Document Processing",
    industry: [
      "manufacturing",
      "logistics",
      "healthcare",
      "construction",
      "financial-services",
      "energy",
      "retail",
      "legal",
      "insurance",
      "real-estate",
    ],
    description:
      "Classify, extract, validate, and route documents from any source — classify by type, extract structured data, and deliver to the right system or person.",
    painPoint:
      "Organizations receive hundreds of documents daily — contracts, invoices, manifests, reports, applications — in different formats (PDF, Word, images, scanned copies). Each document must be read, classified, and manually entered. Document processing consumes entire departments' time.",
    howItWorks: [
      "Agent monitors document sources: email, document folders, scanners, upload portals",
      "Classifies each document by type (invoice, contract, report, form, letter) using content analysis",
      "Extracts relevant data fields based on document type and configured extraction schemas",
      "Validates extracted data against rules and previous records, flagging anomalies",
      "Routes documents to the appropriate system (ERP, CRM, EHR, DMS) or person (by role)",
      "Stores processed documents in a searchable archive with extracted metadata",
    ],
    timeSaved: "90% reduction in document processing time — from 10 minutes to under 1 minute per document",
    accuracyGain: "98% accurate classification and extraction — continuously improving with feedback",
    systemsRequired: ["Document storage system", "Target system (ERP, CRM, EHR)", "Email or scanner source"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "contract-review",
    name: "Contract Review & Analysis",
    industry: ["legal", "financial-services", "insurance", "real-estate", "construction", "manufacturing"],
    description:
      "Analyze contracts for key terms, obligations, risks, and compliance gaps — flagging problematic clauses and summarizing agreements in seconds.",
    painPoint:
      "Attorneys, contract managers, and procurement professionals spend 30-60 minutes reading and analyzing each contract. A 50-page agreement might take 2+ hours to fully review. Critical clauses get missed, and contract review backlogs delay deals by weeks.",
    howItWorks: [
      "Agent ingests contracts from email, document repository, or upload portal in any format",
      "Extracts key terms: parties, effective dates, termination clauses, renewal terms, payment obligations, liability caps",
      "Flags risky clauses: automatic renewal, unilateral amendment, unlimited liability, non-compete restrictions",
      "Compares terms against playbook standards or approved clause libraries",
      "Summarizes the contract in a structured one-page review with risk ratings and recommendations",
      "Generates redlined markups and tracked-change comparisons against templates",
    ],
    timeSaved: "95% faster contract review — 50 pages reviewed in under 60 seconds",
    accuracyGain: "100% clause detection rate — eliminates missed terms and hidden risks",
    systemsRequired: ["Document storage or email", "Contract management system (optional)"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "onboarding",
    name: "Employee & Client Onboarding",
    industry: [
      "financial-services",
      "healthcare",
      "legal",
      "insurance",
      "real-estate",
      "retail",
      "construction",
      "manufacturing",
    ],
    description:
      "Automate onboarding workflows — document collection, form completion, account creation, training assignments, and compliance checks.",
    painPoint:
      "Onboarding new employees or clients requires collecting forms, verifying identity, setting up accounts, assigning training, and conducting compliance checks. Each onboarding cycle involves 15+ manual steps across 5+ systems. HR and operations teams spend 4-6 hours per new hire or client.",
    howItWorks: [
      "Agent sends personalized onboarding packet with forms, policies, and required documents via email or portal",
      "Collects and validates completed forms: W-4, I-9, direct deposit, emergency contacts, NDAs",
      "Verifies identity documents using OCR and government ID validation",
      "Creates accounts in HRIS, payroll, benefits, IT, and facility systems",
      "Assigns required training courses and tracks completion status",
      "Generates onboarding progress dashboard and sends reminders for outstanding items",
    ],
    timeSaved: "70% reduction in onboarding time — from 6 hours to under 2 hours per new hire",
    accuracyGain: "100% form completion and compliance documentation with zero manual chasing",
    systemsRequired: ["HRIS or payroll system", "Email", "Document storage"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "client-intake",
    name: "Client Intake & Engagement",
    industry: ["legal", "financial-services", "insurance", "real-estate", "healthcare"],
    description:
      "Automate new client acquisition workflows — inquiry response, conflict checking, document collection, engagement letters, and account setup.",
    painPoint:
      "New client inquiries arrive through phone, email, and web forms. Intake staff manually enter data, run conflict checks, collect documents, and prepare engagement letters. Each new client takes 45-90 minutes of manual processing before work can begin.",
    howItWorks: [
      "Agent captures client inquiries from web forms, email, and phone transcripts",
      "Sends digital intake forms for client details, preferences, and required documentation",
      "Runs conflict checks against existing client databases and flags potential conflicts",
      "Collects and validates identification documents, KYC/AML information, and compliance forms",
      "Generates engagement letters from approved templates with client-specific terms",
      "Creates client records in CRM, billing, and practice management systems",
    ],
    timeSaved: "75% reduction in client intake time — from 60 minutes to under 15 minutes per client",
    accuracyGain: "100% KYC/AML compliance with complete documentation and audit trail",
    systemsRequired: ["CRM", "Practice management or case management system", "Email"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "payroll-processing",
    name: "Payroll Processing",
    industry: [
      "manufacturing",
      "logistics",
      "healthcare",
      "construction",
      "retail",
      "financial-services",
      "insurance",
      "legal",
    ],
    description:
      "Automate payroll data collection, hours verification, deductions calculation, tax filing, and direct deposit generation.",
    painPoint:
      "Payroll teams manually collect timesheets from multiple systems, verify hours against schedules, calculate overtime and deductions, and generate payroll batches. Each payroll cycle requires 8-12 hours of manual work. Errors in tax calculations or deduction coding cause compliance headaches and employee frustration.",
    howItWorks: [
      "Agent collects time and attendance data from time clocks, timesheets, and schedule systems",
      "Validates hours against configured rules: overtime thresholds, break compliance, shift differentials",
      "Calculates gross pay, deductions, benefits contributions, and tax withholdings",
      "Generates payroll register for review and approval before processing",
      "Subs approved payroll data to payroll system or processor for direct deposit generation",
      "Files payroll taxes and generates W-2s, pay stubs, and year-end reports",
    ],
    timeSaved: "75% reduction in payroll processing time — from 10 hours to under 3 hours per cycle",
    accuracyGain: "99.9% payroll accuracy with automated tax calculation and compliance",
    systemsRequired: ["Payroll system or processor", "Time and attendance system", "HRIS"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "benefits-administration",
    name: "Benefits Administration",
    industry: ["financial-services", "healthcare", "manufacturing", "retail", "legal", "insurance"],
    description:
      "Automate benefits enrollment, eligibility tracking, carrier file exchange, COBRA administration, and open enrollment communications.",
    painPoint:
      "HR teams manage benefits across multiple carriers, each with different file formats and deadlines. Open enrollment requires weeks of manual data entry for plan selections, dependent verifications, and carrier file generation. Eligibility errors lead to claims denials and employee dissatisfaction.",
    howItWorks: [
      "Agent manages open enrollment: sends personalized benefit summaries, collects elections, and validates dependent eligibility",
      "Generates carrier files in required formats with employee elections and demographic data",
      "Tracks eligibility changes: new hires, terminations, qualifying life events",
      "Administers COBRA notifications and premium collection tracking",
      "Reconciles carrier invoices against active enrollments and flags discrepancies",
      "Provides employee self-service portal for plan documents, claims, and coverage verification",
    ],
    timeSaved: "80% reduction in benefits administration time — saves 15+ HR hours during open enrollment",
    accuracyGain: "100% carrier file accuracy with zero eligibility errors",
    systemsRequired: ["HRIS", "Benefits administration platform or carrier portals"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "vendor-management",
    name: "Vendor Management",
    industry: ["manufacturing", "logistics", "construction", "retail", "financial-services"],
    description:
      "Manage vendor onboarding, performance tracking, contract compliance, and relationship management — automatically.",
    painPoint:
      "Procurement teams track vendors across spreadsheets, email threads, and filing cabinets. Vendor onboarding requires collecting W-9s, insurance certificates, and contracts manually. Performance tracking is sporadic at best, and contract compliance issues go unnoticed until renewal.",
    howItWorks: [
      "Agent manages vendor onboarding: sends requests for W-9, insurance certs, and compliance docs",
      "Validates submitted documents against requirements and flags expirations automatically",
      "Tracks vendor performance metrics: on-time delivery, quality scores, response times, pricing competitiveness",
      "Monitors contract compliance: insurance expiration, renewal dates, SLA adherence",
      "Generates vendor scorecards with trended performance data and risk ratings",
      "Sends automated renewal reminders and re-negotiation triggers based on contract dates",
    ],
    timeSaved: "70% reduction in vendor management time — from 4+ hours to under 2 hours weekly",
    accuracyGain: "100% vendor documentation compliance with automated expiration tracking",
    systemsRequired: ["Procurement or ERP system", "Email", "Document storage"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "customer-support-triage",
    name: "Customer Support Triage",
    industry: ["retail", "logistics", "healthcare", "financial-services", "real-estate", "insurance"],
    description:
      "Automatically triage, categorize, and respond to customer support inquiries — routing complex issues to the right team and resolving common requests instantly.",
    painPoint:
      "Customer support teams are overwhelmed by high volumes of repetitive inquiries — order status, account questions, basic troubleshooting. Each inquiry takes 6-8 minutes of reading, researching, and responding. During peak periods, response times stretch to 24+ hours and CSAT scores drop.",
    howItWorks: [
      "Agent monitors support channels: email, chat, web forms, social media, phone transcripts",
      "Classifies each inquiry by intent (order status, account issue, product question, complaint)",
      "Resolves common inquiries instantly from knowledge base: order tracking, password resets, FAQ answers",
      "Escalates complex issues to the appropriate team with a structured summary and context",
      "Sends automated acknowledgments with expected response times and ticket numbers",
      "Analyzes inquiry patterns and identifies knowledge base gaps and process improvements",
    ],
    timeSaved: "60% reduction in support team workload — resolves 40% of inquiries without human touch",
    accuracyGain: "95% accurate triage and routing — issues reach the right team the first time",
    systemsRequired: ["Customer support platform (Zendesk, ServiceNow)", "Knowledge base", "Email/Chat integration"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "lead-response",
    name: "Instant Lead Response",
    industry: ["real-estate", "financial-services", "legal", "insurance", "healthcare"],
    description:
      "Respond to inbound leads instantly via email, text, or chat — qualify, schedule, and route hot leads to the right team member within seconds.",
    painPoint:
      "Inbound leads from websites, referrals, and directories land in a CRM or email inbox. Without an automated response, 80% of leads go cold within 5 minutes. Sales and service teams waste hours on unqualified leads while hot prospects wait and move to competitors.",
    howItWorks: [
      "Agent captures leads from web forms, email, chat widgets, phone calls, and third-party lead sources",
      "Responds within seconds with a personalized message: acknowledging interest, setting expectations, and next steps",
      "Qualifies leads by collecting key information through a structured conversation",
      "Scores leads based on fit criteria, urgency, and engagement level",
      "Routes high-scoring leads to the appropriate team member with full context",
      "Nurtures lower-scoring leads with automated follow-up sequences over time",
    ],
    timeSaved: "95% faster lead response — from 30+ minutes to under 60 seconds",
    accuracyGain: "3.4x more leads converted through instant response and intelligent qualification",
    systemsRequired: ["CRM", "Email/SMS gateway", "Lead source integrations (web form, chat widget)"],
    priceTier: "starter",
    roiTimeline: "1-2 weeks",
  },
  {
    id: "report-generation",
    name: "Automated Report Generation",
    industry: [
      "manufacturing",
      "logistics",
      "healthcare",
      "financial-services",
      "energy",
      "insurance",
      "legal",
      "real-estate",
    ],
    description:
      "Generate scheduled and on-demand reports by pulling data from multiple systems, creating visualizations, and distributing them to stakeholders automatically.",
    painPoint:
      "Managers and analysts spend 5-10 hours per week manually creating reports — exporting data from 3+ systems, building charts in spreadsheets, and emailing PDFs. Report formats drift over time, and data is always a few days stale by the time it's shared.",
    howItWorks: [
      "Agent connects to data sources: ERP, CRM, BI tools, databases, spreadsheets",
      "Pulls data according to configured report schedules and parameters",
      "Applies transformations: aggregations, calculations, comparisons, trend analyses",
      "Generates formatted reports with charts, tables, and executive summaries",
      "Distributes reports via email, Slack, Teams, or dashboard at scheduled intervals",
      "Maintains report version history and allows on-demand ad-hoc report generation",
    ],
    timeSaved: "90% reduction in report generation time — from 5 hours to under 30 minutes per report",
    accuracyGain: "100% consistent report formatting and data accuracy across all distributions",
    systemsRequired: ["Data sources (ERP, CRM, BI)", "Email or messaging platform", "Dashboard or BI tool (optional)"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "email-management",
    name: "Email Management & Auto-Reply",
    industry: [
      "manufacturing",
      "logistics",
      "healthcare",
      "financial-services",
      "energy",
      "retail",
      "legal",
      "insurance",
      "real-estate",
    ],
    description:
      "Automatically triage, categorize, and respond to emails — flagging urgent messages, routing to the right person, and resolving common requests instantly.",
    painPoint:
      "Knowledge workers receive 100+ emails daily and spend 2+ hours reading, categorizing, and responding. Important messages get buried in the noise. Response time to customer and partner emails averages 24+ hours because inbox triage is entirely manual.",
    howItWorks: [
      "Agent monitors email inboxes and classifies each message by intent, urgency, and topic",
      "Flags urgent messages (complaints, escalations, deadlines) for immediate human attention",
      "Resolves common requests via auto-reply: order status, appointment confirmations, FAQ answers, document requests",
      "Routes emails to the appropriate team member or department based on content analysis",
      "Suggests draft responses for complex emails, which the user can approve or edit",
      "Maintains email history and conversation context for continuity",
    ],
    timeSaved: "50% reduction in email processing time — saves 1+ hour per person daily",
    accuracyGain: "95% accurate triage and routing with complete email audit trail",
    systemsRequired: ["Email account (Gmail, Outlook)", "CRM or ticketing system (optional)"],
    priceTier: "starter",
    roiTimeline: "1-2 weeks",
  },
  {
    id: "compliance-monitoring",
    name: "Regulatory Compliance Monitoring",
    industry: ["financial-services", "healthcare", "energy", "insurance"],
    description:
      "Continuously monitor regulatory changes, map them to internal controls, assess impact, and trigger remediation workflows automatically.",
    painPoint:
      "Regulations change constantly across jurisdictions. Compliance teams manually track regulatory publications, assess impact on their controls, and implement changes. A single regulatory change can require 40+ hours of manual analysis and control updates. Most teams are 3-6 months behind on regulatory change management.",
    howItWorks: [
      "Agent monitors regulatory databases, government publications, and industry alerts for relevant changes",
      "Analyzes each change and maps it to affected internal policies, controls, and procedures",
      "Assesses impact severity: critical, moderate, or informational",
      "Generates impact analysis reports with recommended control changes and implementation timelines",
      "Creates remediation tasks assigned to responsible control owners with deadlines",
      "Tracks remediation progress and provides compliance posture dashboards",
    ],
    timeSaved: "80% reduction in regulatory monitoring time — from 15+ hours to under 3 hours weekly",
    accuracyGain: "100% coverage of relevant regulatory changes with zero missed deadlines",
    systemsRequired: ["Compliance management system", "Regulatory database subscriptions"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "expense-reporting",
    name: "Expense Report Processing",
    industry: [
      "manufacturing",
      "logistics",
      "healthcare",
      "financial-services",
      "energy",
      "retail",
      "legal",
      "insurance",
      "real-estate",
    ],
    description:
      "Automate expense report submission, receipt validation, policy compliance checking, approval routing, and reimbursement.",
    painPoint:
      "Employees submit expense reports with paper receipts or scanned images. Finance teams manually review each receipt against policy, calculate totals, check approvals, and process reimbursements. Each report takes 15-20 minutes to process and has a 30% error rate on first submission.",
    howItWorks: [
      "Agent receives expense reports from employees via email, app, or web upload",
      "Extracts receipt data using OCR: merchant, date, amount, category, currency",
      "Validates receipts against expense policy: mileage rates, per diem limits, receipt thresholds",
      "Checks for policy violations: out-of-policy spending, missing receipts, duplicate submissions",
      "Routes approved reports to payroll or AP for reimbursement processing",
      "Generates expense analytics by department, category, and employee",
    ],
    timeSaved: "80% faster expense processing — from 15 minutes to under 3 minutes per report",
    accuracyGain: "95% first-pass approval rate vs 70% manual baseline",
    systemsRequired: ["Expense management system or accounting software", "Email or app for submission"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "lead-scoring",
    name: "Lead Scoring & Prioritization",
    industry: ["real-estate", "financial-services", "legal", "insurance", "healthcare"],
    description:
      "Score and prioritize leads based on behavior, demographics, engagement, and fit — ensuring sales teams focus on the highest-value opportunities.",
    painPoint:
      "Sales teams receive dozens of leads daily but have no systematic way to prioritize. High-value leads get the same response as low-quality inquiries. Sales reps spend 60% of their time on leads that never convert, while their best opportunities wait.",
    howItWorks: [
      "Agent collects lead data from CRM, web behavior, email engagement, and third-party sources",
      "Scores each lead on fit (demographics, company size, role) and intent (page visits, content downloads, email opens)",
      "Applies configurable scoring models: BANT, lead source quality, engagement velocity",
      "Assigns priority tiers: hot, warm, cold, nurture — with recommended next actions",
      "Routes high-priority leads to the right sales rep with full context and suggested outreach",
      "Tracks score trends and conversion rates to continuously optimize the scoring model",
    ],
    timeSaved: "50% less time spent on low-quality leads — sales focus shifts to highest-value opportunities",
    accuracyGain: "3x increase in lead-to-opportunity conversion rate through better prioritization",
    systemsRequired: ["CRM", "Marketing automation or web analytics", "Email engagement data"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "document-generation",
    name: "Automated Document Generation",
    industry: ["legal", "real-estate", "financial-services", "insurance", "healthcare"],
    description:
      "Generate contracts, letters, forms, and reports from templates — populate with client data, apply terms, and manage version control.",
    painPoint:
      "Professionals spend hours creating documents from scratch or copying and pasting from templates. Each document must be manually populated with client details, terms adjusted, and formatting corrected. Version control is non-existent, and document inconsistencies lead to errors and liability risks.",
    howItWorks: [
      "Agent receives document request with client details, transaction parameters, or case information",
      "Selects the appropriate template from approved template library based on document type",
      "Populates template fields with data from CRM, forms, or user-provided information",
      "Applies conditional logic: clauses, terms, and calculations based on transaction parameters",
      "Generates draft document for human review with tracked changes and completeness check",
      "Manages version history and maintains document generation audit trail",
    ],
    timeSaved: "90% faster document creation — from 45 minutes to under 5 minutes per document",
    accuracyGain: "100% template compliance with zero manual data entry errors",
    systemsRequired: ["Template library", "CRM or practice management system", "Document storage"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "vendor-invoice-matching",
    name: "3-Way Invoice Matching",
    industry: ["manufacturing", "logistics", "construction", "retail", "energy"],
    description:
      "Automatically match invoices to purchase orders and receiving documents, flagging discrepancies for resolution before payment.",
    painPoint:
      "AP teams manually compare invoices against POs and receiving reports to verify quantities, prices, and terms. Each 3-way match takes 8-12 minutes. Discrepancies require email chains and phone calls to resolve. Without automated matching, overpayments and duplicate payments slip through.",
    howItWorks: [
      "Agent receives invoice and automatically retrieves the matching PO and receiving record",
      "Compares line items: SKU, quantity, unit price, extended amount, tax, and totals",
      "Flags mismatches by type: price variance, quantity overage, missing PO, unauthorized items",
      "Categorizes discrepancy severity: approve with note, hold for review, or reject outright",
      "Sends discrepancy notifications to the appropriate approver with all context",
      "Tracks approval decisions and posts matched invoices to the payment queue",
    ],
    timeSaved: "85% faster 3-way matching — from 10 minutes to under 2 minutes per invoice",
    accuracyGain: "100% detection of price and quantity discrepancies — no more overpayments",
    systemsRequired: ["ERP or accounting system", "Purchasing system", "Receiving/WMS system"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "customer-feedback-analysis",
    name: "Customer Feedback Analysis",
    industry: ["retail", "logistics", "healthcare", "financial-services", "real-estate", "insurance"],
    description:
      "Analyze customer feedback from surveys, reviews, support tickets, and social media — extracting themes, sentiment, and actionable insights.",
    painPoint:
      "Customer feedback comes from many channels — NPS surveys, online reviews, support tickets, social mentions — and most goes unanalyzed. Teams don't know what customers are saying or whether satisfaction is improving. Negative trends go unnoticed for months.",
    howItWorks: [
      "Agent collects feedback from survey platforms, review sites, support tickets, and social media",
      "Analyzes sentiment (positive, negative, neutral) and identifies emotional drivers",
      "Extracts themes and topics: pricing, quality, support, delivery, features",
      "Tracks sentiment trends over time by channel, product, and customer segment",
      "Flags negative trends and emerging issues with supporting evidence and sample quotes",
      "Generates actionable insight reports with recommended process improvements",
    ],
    timeSaved: "90% faster feedback analysis — from weeks of manual review to real-time dashboards",
    accuracyGain: "95% accurate theme detection and sentiment classification",
    systemsRequired: ["Survey platform", "Customer support system", "Social media monitoring tools"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "contract-lifecycle-management",
    name: "Contract Lifecycle Management",
    industry: ["legal", "financial-services", "insurance", "real-estate", "construction", "manufacturing"],
    description:
      "Manage contracts from creation through renewal or expiration — tracking milestones, obligations, and compliance automatically.",
    painPoint:
      "Contracts are stored in email folders, filing cabinets, and shared drives with no central management. Renewal dates get missed, obligations go unfulfilled, and contract value leaks through auto-renewals and uncapped price escalations. Organizations lose 5-15% of contract value through poor lifecycle management.",
    howItWorks: [
      "Agent ingests contracts from email, uploads, or document repositories and classifies by type and status",
      "Extracts and tracks key dates: effective date, expiration, renewal window, notice period",
      "Monitors obligation fulfillment: reporting requirements, insurance renewals, SLA compliance",
      "Sends automated alerts for upcoming renewals, expirations, and obligations with recommended actions",
      "Generates contract value reports: total contract value, remaining value, price escalations applied",
      "Maintains a searchable contract repository with full-text search and metadata filtering",
    ],
    timeSaved: "70% reduction in contract administration time — saves 10+ hours per contract manager weekly",
    accuracyGain: "100% renewal and obligation tracking — zero missed dates or auto-renewal surprises",
    systemsRequired: ["Contract management system or database", "Document storage", "Email"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "budget-tracking",
    name: "Budget Tracking & Forecasting",
    industry: ["construction", "manufacturing", "energy", "financial-services", "healthcare"],
    description:
      "Track actual spend against budgets in real time, forecast overruns, and alert stakeholders before budgets are exceeded.",
    painPoint:
      "Project and department budgets are set in spreadsheets at the start of the year and checked quarterly. Actual spend is scattered across PO systems, credit card statements, and expense reports. By the time overspend is visible, it's too late to course-correct.",
    howItWorks: [
      "Agent connects to financial systems: ERP, AP, payroll, expense management, procurement",
      "Aggregates actual spend by budget category, department, project, and cost center",
      "Compares actual against budgeted amounts and calculates variance percentages",
      "Forecasts period-end spend based on current burn rate and committed but not yet incurred costs",
      "Flags categories approaching or exceeding budget with percentage thresholds and escalation paths",
      "Generates budget dashboards with real-time visibility into remaining balances and forecasts",
    ],
    timeSaved: "80% reduction in budget tracking time — from quarterly spreadsheet updates to real-time dashboards",
    accuracyGain: "Real-time budget visibility with automated alerts before overruns occur",
    systemsRequired: ["ERP or accounting system", "Budget management tool or spreadsheet", "Expense management system"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "time-tracking",
    name: "Automated Time Tracking",
    industry: ["legal", "financial-services", "consulting", "construction", "healthcare", "insurance"],
    description:
      "Capture billable and non-billable time automatically from calendar events, system activity, and manual entries — with intelligent categorization.",
    painPoint:
      "Professionals are expected to track their time in 6-minute increments but forget to log as they switch between tasks. Billable time leakage of 5-10% is considered normal. End-of-week time entry sessions take 30-60 minutes and produce inaccurate recall-based entries.",
    howItWorks: [
      "Agent captures time from calendar events, email activity, document access, and system logins",
      "Suggests time entries based on activity patterns and calendar context",
      "Categorizes time by client, project, task type, and billable status",
      "Flags unlogged time periods and sends gentle reminders throughout the day",
      "Validates entries against billable hour targets and weekly minimums",
      "Exports approved time entries to billing, payroll, and project management systems",
    ],
    timeSaved: "60% less time spent on time entry — from 30+ minutes weekly to under 10 minutes",
    accuracyGain: "Captures 98% of billable time vs 90% industry average — recovers 5-8% of revenue",
    systemsRequired: ["Calendar system", "Practice management or billing system", "Email and document activity"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "invoice-collections",
    name: "Automated Invoice Collections",
    industry: ["manufacturing", "logistics", "retail", "financial-services", "insurance", "legal", "real-estate"],
    description:
      "Automate accounts receivable collections — send reminders, escalate overdue invoices, negotiate payment plans, and reconcile payments.",
    painPoint:
      "Finance teams manually send payment reminders, make collection calls, and negotiate payment plans. Each overdue invoice requires 5+ touchpoints over 30-60 days. Collections consume 15+ hours weekly, and inconsistent follow-through delays cash flow by weeks.",
    howItWorks: [
      "Agent monitors accounts receivable aging and identifies overdue invoices by severity",
      "Sends automated reminders at configured intervals: 3 days overdue, 7 days, 15 days, 30 days",
      "Escalates to phone call or manager intervention for invoices past 45 days",
      "Negotiates payment plans based on configured terms, offering installment options",
      "Processes payments received via payment links, ACH, or credit card and reconciles against invoices",
      "Generates collections performance dashboards: DSO, collection effectiveness, and aging trends",
    ],
    timeSaved: "70% reduction in collections effort — from 15 hours to under 5 hours weekly",
    accuracyGain: "DSO reduction of 12-18 days through consistent, timely follow-up",
    systemsRequired: ["Accounting or ERP system", "Email", "Payment processor or gateway"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "audit-trail-generation",
    name: "Audit Trail Generation",
    industry: ["financial-services", "healthcare", "insurance", "energy", "legal"],
    description:
      "Generate comprehensive audit trails for compliance — tracking access, changes, approvals, and document history across systems.",
    painPoint:
      "Compliance and audit teams spend weeks manually assembling evidence trails: pulling access logs, change history, approval records, and document versions from multiple systems. Each audit cycle requires 100+ person-hours of evidence gathering. Missing or incomplete trails result in audit findings.",
    howItWorks: [
      "Agent connects to monitored systems and continuously captures audit events: access, changes, approvals, exports",
      "Aggregates events into a unified audit log with timestamps, user IDs, system sources, and action details",
      "Correlates related events across systems to show complete transaction history",
      "Generates audit evidence packages for specific time ranges, users, or transactions on demand",
      "Formats evidence for specific audit standards: SOC 2, HIPAA, SOX, GDPR, PCI DSS",
      "Maintains immutable audit log with tamper-evident record-keeping",
    ],
    timeSaved: "90% faster audit evidence collection — from weeks to hours for any audit request",
    accuracyGain: "100% audit trail completeness with no gaps in evidence coverage",
    systemsRequired: ["Audit logging system or SIEM", "Application and system event sources"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "payment-reconciliation",
    name: "Payment Reconciliation",
    industry: ["financial-services", "retail", "insurance", "logistics", "real-estate"],
    description:
      "Automatically reconcile payments received against invoices, bank deposits, and accounting entries — flagging discrepancies in real time.",
    painPoint:
      "Finance teams manually match bank deposits to invoices and accounting entries. Each day's reconciliation takes 2-4 hours of comparing spreadsheets. Unmatched payments, short-pays, and over-pays go unnoticed for weeks, causing cash flow reporting inaccuracies.",
    howItWorks: [
      "Agent ingests bank statement transactions and invoice/payment data from accounting system",
      "Matches deposits to invoices by amount, reference number, customer name, and date",
      "Flags discrepancies: partial payments, over-payments, unidentified deposits, missing payments",
      "Handles common scenarios: consolidated payments, credit memos, chargebacks, refunds",
      "Generates reconciliation reports with matched, unmatched, and exception line items",
      "Posts reconciled entries to the general ledger with complete audit trail",
    ],
    timeSaved: "85% faster reconciliation — from 3 hours daily to under 30 minutes",
    accuracyGain: "99.9% reconciliation accuracy with real-time discrepancy detection",
    systemsRequired: ["Accounting or ERP system", "Bank feed or statement import", "Payment processor data"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "recruitment-screening",
    name: "Recruitment Screening",
    industry: ["financial-services", "healthcare", "manufacturing", "retail", "legal", "insurance"],
    description:
      "Automate candidate screening, resume parsing, skills assessment, and interview scheduling — accelerating time-to-hire.",
    painPoint:
      "HR teams review hundreds of resumes for each open position. Screening takes 5-10 minutes per resume. Coordinating interviews requires 8+ emails across multiple calendars. Time-to-hire averages 45 days, and good candidates accept other offers during the slow process.",
    howItWorks: [
      "Agent receives incoming applications from job boards, career sites, and email",
      "Parses resumes to extract experience, skills, education, certifications, and contact details",
      "Scores candidates against job requirements using weighted criteria configurable per role",
      "Flags top candidates for human review with a structured summary and match percentage",
      "Schedules interviews via automated calendar coordination across interviewers and candidates",
      "Sends rejection letters to unqualified candidates and keeps them in talent pool for future roles",
    ],
    timeSaved: "70% faster screening cycle — from 10 minutes to under 3 minutes per candidate",
    accuracyGain: "3x more qualified candidates identified per hour of recruiter time",
    systemsRequired: ["Applicant tracking system or HRIS", "Email/Calendar system", "Job board integrations"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "tax-preparation",
    name: "Tax Preparation Support",
    industry: ["financial-services", "legal", "insurance", "real-estate"],
    description:
      "Automate tax data collection, calculate estimates, identify deductions, and prepare filings — reducing tax season workload.",
    painPoint:
      "Tax teams spend January through April collecting documents from clients, entering data into tax software, calculating estimates, and preparing returns. Each return takes 4-8 hours of manual work. Document requests and follow-ups consume 30% of tax preparation time.",
    howItWorks: [
      "Agent sends automated document requests to clients with checklists based on their tax situation",
      "Collects and categorizes documents: W-2s, 1099s, receipts, prior returns, bank statements",
      "Extracts financial data from collected documents using OCR and validation rules",
      "Populates tax software with extracted data, organized by schedule and form type",
      "Calculates estimated tax payments, identifies missing deductions, and flags anomalies",
      "Generates organizer summaries and review-ready return packages",
    ],
    timeSaved: "50% reduction in tax preparation time — saves 2-4 hours per return",
    accuracyGain: "95% reduction in data entry errors and missed deduction identification",
    systemsRequired: ["Tax preparation software", "Document management system", "Email"],
    priceTier: "growth",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "product-data-enrichment",
    name: "Product Data Enrichment",
    industry: ["retail", "manufacturing", "logistics", "ecommerce"],
    description:
      "Enrich product data with descriptions, specifications, images, and categorization from supplier feeds, catalogs, and web sources.",
    painPoint:
      "Retailers and manufacturers receive product data from suppliers in inconsistent formats: spreadsheets, PDF spec sheets, and web pages. Each product requires 15-30 minutes of manual data entry and enrichment. Product pages are incomplete, hurting SEO and conversion rates.",
    howItWorks: [
      "Agent ingests product data from supplier feeds, spec sheets, and catalog PDFs",
      "Extracts structured attributes: dimensions, weight, materials, colors, SKU, UPC, manufacturer info",
      "Enriches product data from web sources: manufacturer websites, competitor listings, review sites",
      "Generates product descriptions from specifications and feature lists",
      "Validates data completeness and flags missing critical attributes",
      "Pushes enriched product data to ecommerce platforms, ERPs, and marketplaces",
    ],
    timeSaved: "85% faster product data setup — from 20 minutes to under 3 minutes per product",
    accuracyGain: "99% attribute completeness with consistent product data across all channels",
    systemsRequired: ["Ecommerce platform or PIM", "Supplier data sources", "Web scraping capability"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "service-desk-automation",
    name: "IT Service Desk Automation",
    industry: ["financial-services", "healthcare", "manufacturing", "energy", "insurance"],
    description:
      "Automate IT service desk triage, password resets, account provisioning, and common issue resolution — reducing ticket volume and response times.",
    painPoint:
      "IT service desks handle 50-200 tickets daily. Password resets account for 30% of all tickets but take 5-10 minutes each. Account provisioning requires manual steps across 3+ systems. SLAs are missed because Level 1 agents are overwhelmed with repetitive requests.",
    howItWorks: [
      "Agent monitors service desk channels: ticket system, chat, email, phone transcripts",
      "Resolves common issues instantly: password resets, account unlocks, access requests, software installs",
      "Triage technical issues by symptom and routes to the appropriate Level 2 team",
      "Provisions new user accounts across HRIS, directory, email, and application systems",
      "Generates knowledge base articles from resolved tickets for self-service",
      "Tracks SLA compliance, ticket volumes, and resolution patterns",
    ],
    timeSaved: "60% reduction in Level 1 ticket volume — resolves 40% of tickets without human touch",
    accuracyGain: "95% first-contact resolution rate for automated requests",
    systemsRequired: ["ITSM platform (ServiceNow, Jira)", "Identity and access management", "Email/Chat"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "procurement-optimization",
    name: "Procurement Optimization",
    industry: ["manufacturing", "construction", "energy", "retail", "logistics"],
    description:
      "Analyze procurement data to identify savings opportunities, optimize supplier mix, consolidate spend, and negotiate better terms.",
    painPoint:
      "Procurement teams manage hundreds of suppliers and thousands of line items across categories. Spend analysis is done annually in spreadsheets, if at all. Maverick spend, supplier consolidation opportunities, and price variance issues go undetected, costing 5-15% in addressable savings.",
    howItWorks: [
      "Agent ingests procurement data: POs, supplier invoices, contracts, and expense reports",
      "Analyzes spend by category, supplier, department, and cost center",
      "Identifies savings opportunities: consolidation, volume discounts, substitute products, contract compliance gaps",
      "Tracks price variance across suppliers and over time for key commodities",
      "Generates category management reports with savings targets and action plans",
      "Monitors maverick spend and recommends preferred supplier sourcing",
    ],
    timeSaved: "80% faster spend analysis — from weeks of manual work to automated dashboards",
    accuracyGain: "5-15% addressable savings identified through comprehensive spend visibility",
    systemsRequired: ["ERP or procurement system", "Supplier contract repository", "Spend analytics platform"],
    priceTier: "scale",
    roiTimeline: "12-20 weeks",
  },
  {
    id: "warranty-claims-processing",
    name: "Warranty Claims Processing",
    industry: ["manufacturing", "retail", "automotive", "energy"],
    description:
      "Automate warranty claim intake, validation, approval, and tracking — reducing processing time and improving customer satisfaction.",
    painPoint:
      "Warranty claims arrive via email, web forms, and paper. Each claim requires manual validation against warranty terms, product registration data, and claim history. Processing takes 20-30 minutes per claim. Backlogs of 300+ claims are common, and customers wait weeks for resolution.",
    howItWorks: [
      "Agent receives warranty claims from web form, email, or partner portal",
      "Validates claim against warranty terms: product registration, purchase date, coverage period, exclusions",
      "Checks claim history for duplicate or pattern claims",
      "Assigns claim severity and routes to appropriate claims handler",
      "Generates approval or denial letters with supporting evidence",
      "Tracks claim resolution time and generates warranty performance reports",
    ],
    timeSaved: "70% faster warranty processing — from 25 minutes to under 8 minutes per claim",
    accuracyGain: "95% reduction in invalid claim approvals through automated validation",
    systemsRequired: ["Warranty management system", "CRM", "ERP for product and customer data"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "visitor-management",
    name: "Visitor Management",
    industry: ["manufacturing", "healthcare", "financial-services", "energy", "legal"],
    description:
      "Automate visitor check-in, badge printing, host notification, and compliance logging for secure facilities.",
    painPoint:
      "Front desk staff manually check visitors in, call hosts, print badges, and maintain visitor logs. Each visitor takes 5-8 minutes of staff time. During peak hours, visitors wait in line and hosts are interrupted. Visitor logs are paper-based and not searchable for audit purposes.",
    howItWorks: [
      "Agent manages visitor pre-registration via email or web portal with photo upload and NDA signing",
      "Handles on-site check-in via self-service kiosk or QR code scan",
      "Prints visitor badges with photo, host name, and access level",
      "Notifies hosts via Slack, Teams, or SMS when their visitor arrives",
      "Tracks visitor movements within facility based on access log data",
      "Maintains searchable visitor log with check-in/out times, host details, and purpose of visit",
    ],
    timeSaved: "80% reduction in front desk visitor processing — from 5 minutes to under 1 minute per visitor",
    accuracyGain: "100% visitor compliance logging with complete searchable audit trail",
    systemsRequired: ["Visitor management system or kiosk", "Badge printer", "Slack/Teams/SMS for host notification"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "supplier-risk-monitoring",
    name: "Supplier Risk Monitoring",
    industry: ["manufacturing", "energy", "logistics", "construction", "retail"],
    description:
      "Continuously monitor supplier financial health, compliance status, geopolitical risk, and performance — alerting on changes that could disrupt supply.",
    painPoint:
      "Supply chain disruptions from supplier bankruptcy, compliance failures, or geopolitical events cost companies millions. Most organizations don't have real-time visibility into supplier risk. Risk is discovered when a shipment doesn't arrive — too late for contingency planning.",
    howItWorks: [
      "Agent monitors supplier data sources: financial reports, credit ratings, news, compliance databases, geopolitical feeds",
      "Tracks supplier performance metrics: on-time delivery, quality scores, responsiveness, capacity utilization",
      "Scores each supplier on financial stability, compliance, operational, and geopolitical risk dimensions",
      "Alerts on risk score changes, negative news, credit downgrades, or compliance violations",
      "Generates risk dashboards showing portfolio-level and supplier-level risk exposure",
      "Recommends alternative suppliers for high-risk single-source dependencies",
    ],
    timeSaved: "90% reduction in manual supplier research time — from 5+ hours to real-time monitoring",
    accuracyGain: "Early warning on 85% of supplier disruptions before they impact operations",
    systemsRequired: ["Supplier management system", "Financial data subscriptions", "News and risk data feeds"],
    priceTier: "scale",
    roiTimeline: "12-20 weeks",
  },
  {
    id: "customer-segmentation",
    name: "Customer Segmentation & Analytics",
    industry: ["retail", "financial-services", "insurance", "real-estate", "healthcare"],
    description:
      "Segment customers by behavior, value, demographics, and engagement — delivering personalized marketing, service, and product recommendations.",
    painPoint:
      "Marketing and sales teams treat all customers the same, sending generic campaigns to broad lists. Without segmentation, high-value customers get the same treatment as low-engagement ones. Personalization is limited because teams lack the time and tools to analyze customer data and create meaningful segments.",
    howItWorks: [
      "Agent connects to customer data sources: CRM, transaction history, web analytics, support history",
      "Analyzes customer behavior: purchase patterns, channel preference, engagement frequency, lifetime value",
      "Creates segments based on RFM (recency, frequency, monetary), lifecycle stage, and behavioral attributes",
      "Generates segment profiles with descriptive statistics and key differentiators",
      "Pushes segments to marketing, sales, and service platforms for targeted campaigns",
      "Tracks segment performance and evolution over time, updating segments automatically",
    ],
    timeSaved: "90% faster segmentation — from weeks of manual analysis to automated, real-time segments",
    accuracyGain: "3-5x improvement in campaign response rates through targeted segmentation",
    systemsRequired: ["CRM", "Marketing automation platform", "Web analytics", "Data warehouse or BI tool"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "regulatory-filing",
    name: "Regulatory Filing Preparation",
    industry: ["financial-services", "energy", "healthcare", "insurance"],
    description:
      "Prepare and submit regulatory filings by collecting required data, validating against rules, generating forms, and maintaining submission history.",
    painPoint:
      "Regulatory filing teams manually collect data from multiple systems, populate forms, validate against rules, and submit through government portals. Each filing cycle takes 2-4 weeks of intensive work. Data inconsistencies across sources cause submission rejections and resubmission cycles that add weeks.",
    howItWorks: [
      "Agent identifies upcoming filing requirements from regulatory calendars and obligation tracking",
      "Collects required data from financial, operational, and compliance systems",
      "Validates data against filing rules: completeness, consistency, cross-source verification",
      "Populates regulatory forms with validated data in required formats (XBRL, PDF, CSV)",
      "Generates submission packages with supporting documentation and attestations",
      "Submits via regulatory portal or EDI, tracking submission status and storing confirmations",
    ],
    timeSaved: "75% faster filing preparation — from 3 weeks to under 1 week per filing cycle",
    accuracyGain: "99% first-pass submission acceptance vs 70% industry average",
    systemsRequired: ["Regulatory filing software", "Financial reporting system", "Compliance management system"],
    priceTier: "scale",
    roiTimeline: "12-20 weeks",
  },
  {
    id: "sales-order-processing",
    name: "Sales Order Processing",
    industry: ["manufacturing", "logistics", "retail", "energy", "construction"],
    description:
      "Automate sales order intake, validation, credit check, inventory allocation, and order confirmation — accelerating order-to-cash cycles.",
    painPoint:
      "Sales orders arrive via email, EDI, web portal, and phone. Each order requires manual entry into the ERP, credit check, inventory availability check, and order confirmation. Processing a single order takes 10-18 minutes. Errors in order entry cause shipment delays and customer complaints.",
    howItWorks: [
      "Agent captures orders from email, EDI, web forms, and sales rep entries",
      "Validates order details: customer info, product codes, quantities, pricing, delivery addresses",
      "Checks credit status and inventory availability in real time",
      "Allocates inventory and reserves stock for the order",
      "Generates order confirmation with pricing, delivery dates, and order terms",
      "Routes confirmed orders to fulfillment, picking, and shipping systems",
    ],
    timeSaved: "80% faster order processing — from 15 minutes to under 3 minutes per order",
    accuracyGain: "99.5% order accuracy with zero entry errors",
    systemsRequired: ["ERP or order management system", "CRM", "Inventory/WMS system"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "employee-expense-audit",
    name: "Employee Expense Audit",
    industry: ["financial-services", "legal", "healthcare", "manufacturing", "insurance"],
    description:
      "Audit employee expense reports for policy violations, duplicate submissions, and suspicious patterns — automatically flagging risks.",
    painPoint:
      "Finance teams manually review expense reports for policy compliance and fraud indicators. Each report takes 5-10 minutes to review, but subtle violations slip through. Studies show 10-20% of expense reports contain some form of policy violation or error.",
    howItWorks: [
      "Agent receives approved expense reports and applies audit rules to each line item",
      "Checks for policy violations: out-of-policy categories, exceeding limits, missing receipts",
      "Flags potential duplicate submissions: same receipt, same amount, close dates across employees",
      "Identifies suspicious patterns: round numbers, weekend spending, frequent just-over-limit amounts",
      "Scores each report for audit risk and prioritizes high-risk reports for detailed review",
      "Generates audit summary with flagged items, supporting evidence, and recommended actions",
    ],
    timeSaved: "70% faster expense audit — from 8 minutes to under 3 minutes per report",
    accuracyGain: "3x more policy violations detected compared to manual review alone",
    systemsRequired: ["Expense management system", "Accounting system", "Corporate card data"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "purchase-requisition-workflow",
    name: "Purchase Requisition Workflow",
    industry: ["manufacturing", "construction", "energy", "healthcare", "retail"],
    description:
      "Automate purchase requisition creation, approval routing, budget checking, and PO conversion — eliminating manual approval chains.",
    painPoint:
      "Employees submit purchase requests via email. Each request requires manual budget check, manager approval, and procurement team review. Approval chains take 2-5 days. Requestors follow up by email, and approved requests get lost before conversion to POs.",
    howItWorks: [
      "Agent captures purchase requests from email, web form, or Slack/Teams message",
      "Validates request details: item description, quantity, estimated cost, vendor, business justification",
      "Checks remaining budget against request total and flags over-budget requests",
      "Routes requests through configurable approval chains based on amount and category",
      "Tracks approval status and sends reminders to approvers",
      "Converts approved requests into POs and notifies requestors with PO numbers",
    ],
    timeSaved: "75% faster requisition-to-PO cycle — from 3 days to under 6 hours",
    accuracyGain: "100% budget checking before approval — eliminates over-budget purchases",
    systemsRequired: ["ERP or procurement system", "Email", "Slack/Teams integration (optional)"],
    priceTier: "starter",
    roiTimeline: "2-4 weeks",
  },
  {
    id: "document-compliance-check",
    name: "Document Compliance Checking",
    industry: ["financial-services", "healthcare", "legal", "insurance", "energy"],
    description:
      "Automatically check documents for compliance with regulatory, policy, and formatting requirements — flagging violations before submission or filing.",
    painPoint:
      "Documents submitted for compliance review — contracts, filings, disclosures, reports — must meet specific requirements. Compliance teams read each document manually, checking for required clauses, formatting, and content rules. Each review takes 20-45 minutes, and compliance bottlenecks delay business transactions.",
    howItWorks: [
      "Agent receives documents for compliance review and identifies the applicable standard or regulation",
      "Checks document structure against required elements: mandatory clauses, disclaimers, formatting, signatures",
      "Validates content against policy: restricted terms, required language, disclosure requirements",
      "Evaluates readability, formatting consistency, and accessibility compliance",
      "Flags violations with specific clause references and correction suggestions",
      "Generates compliance review report with pass/fail status and detailed findings",
    ],
    timeSaved: "90% faster compliance review — from 30 minutes to under 3 minutes per document",
    accuracyGain: "100% coverage of compliance requirements — zero missed clauses or disclaimers",
    systemsRequired: ["Document management system", "Compliance rules engine or policy database"],
    priceTier: "scale",
    roiTimeline: "8-16 weeks",
  },
  {
    id: "project-status-reporting",
    name: "Project Status Reporting",
    industry: ["construction", "manufacturing", "energy", "financial-services", "healthcare"],
    description:
      "Automate project status report generation by collecting progress data, milestones, risks, and financials from project management systems.",
    painPoint:
      "Project managers spend 4-8 hours weekly compiling status reports: pulling schedule updates from MS Project or Jira, financial data from ERP, and risk logs from spreadsheets. Reports are formatted inconsistently, and stakeholders receive stale information.",
    howItWorks: [
      "Agent connects to project management tools, financial systems, and risk registers",
      "Collects project metrics: schedule progress, milestone completion, budget spent, resource utilization",
      "Tracks open risks, issues, and action items with status updates",
      "Generates formatted status reports with project health indicators (RAG status)",
      "Distributes reports to stakeholders via email, Slack, or dashboard at scheduled intervals",
      "Maintains report archive for trend analysis and stakeholder reference",
    ],
    timeSaved: "80% faster status reporting — from 5 hours to under 1 hour per report",
    accuracyGain: "100% consistent reporting format with real-time data across all reports",
    systemsRequired: ["Project management software (Jira, MS Project)", "ERP for financial data", "Email/Slack"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
  {
    id: "order-fulfillment",
    name: "Order Fulfillment Automation",
    industry: ["retail", "logistics", "manufacturing", "ecommerce"],
    description:
      "Automate order fulfillment from picking through packing and shipping — generating pick lists, packing slips, and shipping labels automatically.",
    painPoint:
      "Fulfillment teams pick orders from paper lists, manually pack them, and generate shipping labels one at a time. Picking errors cause wrong-item shipments. Packing slips and labels are printed individually. Overnight fulfillment requires night shifts of manual labor.",
    howItWorks: [
      "Agent receives confirmed orders from the order management system",
      "Generates optimized pick lists sorted by warehouse location to minimize travel time",
      "Produces packing slips, shipping labels, and assembly instructions for each order",
      "Validates picked items against order lines before packing",
      "Prints or sends digital labels to label printers or mobile devices",
      "Updates inventory and order status in real time as items are packed and shipped",
    ],
    timeSaved: "60% faster fulfillment cycle — from 15 minutes to under 6 minutes per order",
    accuracyGain: "99.8% picking accuracy with barcode and weight validation",
    systemsRequired: ["WMS or order management system", "Label printer or mobile device", "Shipping carrier integration"],
    priceTier: "growth",
    roiTimeline: "6-12 weeks",
  },
  {
    id: "invoice-reconciliation",
    name: "Invoice-to-Payment Reconciliation",
    industry: ["financial-services", "manufacturing", "logistics", "retail", "insurance"],
    description:
      "Reconcile paid invoices against bank statements and accounting entries — matching payments, identifying discrepancies, and resolving exceptions.",
    painPoint:
      "Finance teams manually match each paid invoice to bank statement lines and accounting entries. The process takes 2-4 hours daily. Unmatched payments, duplicate payments, and short-payments accumulate, requiring end-of-month deep dives to clear.",
    howItWorks: [
      "Agent ingests paid invoices, bank statement transactions, and accounting journal entries",
      "Matches payments to invoices using amount, reference number, customer, and payment date",
      "Identifies exceptions: partial payments, overpayments, duplicate payments, unidentified receipts",
      "Handles common reconciliation scenarios: credit memos, chargebacks, refunds, consolidations",
      "Generates reconciliation statements with detailed exception log and resolution workflows",
      "Posts finalized reconciliations to the general ledger with full audit trail",
    ],
    timeSaved: "85% faster invoice reconciliation — from 3 hours to under 30 minutes daily",
    accuracyGain: "99.9% reconciliation accuracy with real-time exception flagging",
    systemsRequired: ["Accounting or ERP system", "Bank feed or statement data", "Payment processor data"],
    priceTier: "growth",
    roiTimeline: "4-8 weeks",
  },
];