import { createDocuSignClient } from "./client"; import type { ActionDefinition } from "../salesforce/actions";
export const docusignActions: ActionDefinition[] = [
  // ─── Understand / Read ─────────────────────────────────────────────
  { name: "getDocuSignAccountInfo", description: "Get DocuSign account information", inputSchema: { type: "object", properties: {} }, handler: async (config) => createDocuSignClient(config).getAccountInfo() },
  { name: "listDocuSignUsers", description: "List users in the DocuSign account", inputSchema: { type: "object", properties: {} }, handler: async (config) => createDocuSignClient(config).listUsers() },
  { name: "listDocuSignBrands", description: "List DocuSign account brands", inputSchema: { type: "object", properties: {} }, handler: async (config) => createDocuSignClient(config).listBrands() },
  { name: "getDocuSignBrand", description: "Get a DocuSign brand by id", inputSchema: { type: "object", properties: { brandId: { type: "string" } }, required: ["brandId"] }, handler: async (config, p) => createDocuSignClient(config).getBrand(p.brandId) },
  { name: "getDocuSignTemplate", description: "Get a DocuSign template by id", inputSchema: { type: "object", properties: { templateId: { type: "string" } }, required: ["templateId"] }, handler: async (config, p) => createDocuSignClient(config).getTemplate(p.templateId) },
  { name: "getDocuSignEnvelopeAudit", description: "Get the audit trail for an envelope", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => createDocuSignClient(config).getEnvelopeAudit(p.id) },
  { name: "listDocuSignFolders", description: "List DocuSign account folders", inputSchema: { type: "object", properties: {} }, handler: async (config) => createDocuSignClient(config).listFolders() },
  { name: "getDocuSignFolder", description: "Get a DocuSign folder by id", inputSchema: { type: "object", properties: { folderId: { type: "string" } }, required: ["folderId"] }, handler: async (config, p) => createDocuSignClient(config).getFolder(p.folderId) },
  { name: "getDocuSignEnvelopeCustomFields", description: "Get custom fields on an envelope", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => createDocuSignClient(config).getEnvelopeCustomFields(p.id) },
  { name: "listDocuSignSigningGroups", description: "List DocuSign signing groups", inputSchema: { type: "object", properties: {} }, handler: async (config) => createDocuSignClient(config).listSigningGroups() },
  { name: "getDocuSignEnvelopeEnhanced", description: "Get an envelope with recipients, documents, custom fields and audit trail", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => createDocuSignClient(config).getEnvelopeEnhanced(p.id) },

  // ─── Monitor ───────────────────────────────────────────────────────
  { name: "listDocuSignEnvelopeStatusChanges", description: "List envelopes changed in a date window, optionally filtered by status/folder", inputSchema: { type: "object", properties: { fromDate: { type: "string" }, toDate: { type: "string" }, status: { type: "string" }, folderIds: { type: "array", items: { type: "string" } } } }, handler: async (config, p) => createDocuSignClient(config).listEnvelopeStatusChanges(p) },

  // ─── Automate / Write ──────────────────────────────────────────────
  { name: "createDocuSignEnvelopeFromTemplate", description: "Create and send an envelope from a template with roles", inputSchema: { type: "object", properties: { templateId: { type: "string" }, templateRoles: { type: "array", items: { type: "object" } }, emailSubject: { type: "string" }, emailBlurb: { type: "string" } }, required: ["templateId", "templateRoles"] }, handler: async (config, p) => createDocuSignClient(config).createEnvelopeFromTemplate(p) },
  { name: "sendDocuSignEnvelopeFromUrl", description: "Send an envelope with documents hosted at URLs, signing tabs and carbon copies", inputSchema: { type: "object", properties: { emailSubject: { type: "string" }, emailBlurb: { type: "string" }, documents: { type: "array" }, recipients: { type: "array" }, carbonCopies: { type: "array" } }, required: ["emailSubject", "documents", "recipients"] }, handler: async (config, p) => createDocuSignClient(config).sendEnvelopeFromUrl(p) },
  { name: "updateDocuSignEnvelope", description: "Update an envelope (correct or resend)", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => { const { id, ...rest } = p; return createDocuSignClient(config).updateEnvelope(id, rest); } },
  { name: "updateDocuSignRecipients", description: "Update recipients on an envelope", inputSchema: { type: "object", properties: { id: { type: "string" }, recipients: { type: "array" } }, required: ["id", "recipients"] }, handler: async (config, p) => createDocuSignClient(config).updateRecipients(p.id, p.recipients) },
  { name: "createDocuSignTemplate", description: "Create a reusable DocuSign template", inputSchema: { type: "object", properties: {} }, handler: async (config, p) => createDocuSignClient(config).createTemplate(p) },
  { name: "downloadDocuSignDocument", description: "Download a single envelope document", inputSchema: { type: "object", properties: { id: { type: "string" }, docId: { type: "string" } }, required: ["id", "docId"] }, handler: async (config, p) => createDocuSignClient(config).downloadDocument(p.id, p.docId) },
  { name: "getDocuSignCombinedDocument", description: "Download all envelope documents combined into one PDF", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => createDocuSignClient(config).getCombinedDocument(p.id) },
  { name: "voidDocuSignEnvelope", description: "Void an envelope with a reason", inputSchema: { type: "object", properties: { id: { type: "string" }, reason: { type: "string" } }, required: ["id", "reason"] }, handler: async (config, p) => createDocuSignClient(config).voidEnvelope(p.id, p.reason) },

  // ─── Existing surface (kept) ───────────────────────────────────────
  { name: "listDocuSignEnvelopes", description: "List DocuSign envelopes", inputSchema: { type: "object", properties: { fromDate: { type: "string" } } }, handler: async (config, params) => { const c = createDocuSignClient(config); return c.listEnvelopes(params.fromDate); } },
  { name: "sendDocuSignEnvelope", description: "Send DocuSign envelope", inputSchema: { type: "object", properties: { emailSubject: { type: "string" }, documents: { type: "array" }, recipients: { type: "object" } }, required: ["emailSubject"] }, handler: async (config, params) => { const c = createDocuSignClient(config); return c.sendEnvelope(params); } },
  { name: "getDocuSignEnvelope", description: "Get DocuSign envelope status", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, params) => { const c = createDocuSignClient(config); return c.getEnvelope(params.id); } },
  { name: "listDocuSignRecipients", description: "Get envelope recipients with signing status", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => createDocuSignClient(config).listRecipients(p.id) },
  { name: "getDocuSignEnvelopeDocuments", description: "List documents attached to an envelope", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] }, handler: async (config, p) => createDocuSignClient(config).getEnvelopeDocuments(p.id) },
  { name: "docusignHealthCheck", description: "Check DocuSign connection", inputSchema: { type: "object", properties: {} }, handler: async (config) => { const c = createDocuSignClient(config); return { healthy: await c.healthCheck(), provider: "docusign" }; } },
];
